import { QuestionData } from "./questions-data";

const PASSAGE_YOGA_AYURVEDA = `India's heritage of wellness traditions—seen in Yoga, Ayurveda, Siddha, and Unani—forms a layered blend of philosophy, physiology, and metaphysical thought. Rather than remaining frozen in time, these systems have continuously adapted, negotiating their place within local practice and global health conversations. Central to this worldview is the belief that the body is not merely a biological machine but a field of interlinked rhythms and energies. Yoga, shaped by Patanjali's Yoga Sutras, is not simply a set of postures; it is a comprehensive discipline intended to align body, mind, and consciousness. In contemporary settings, however, Yoga has often been commercialized, especially outside India, where its philosophical grounding is frequently reduced to fitness routines or stress-management tools. While this shift has expanded global appeal, it also triggers concerns about cultural appropriation and loss of intellectual depth.

Ayurveda views illness as an imbalance of the tridosha—vata, pitta, and kapha—forces said to govern bodily function. It emphasizes prakriti (constitution), ahara (diet), and dinacharya (daily regimen) as pillars of preventive care. Unlike allopathy's symptom-focused interventions, Indian traditional medicine aims to restore equilibrium within the body's internal ecology. This approach resonates with modern interest in personalized, preventive medicine, though the biomedical community often remains skeptical due to differences in method and proof. Government support for AYUSH reflects renewed institutional attention, yet critics warn against unquestioning promotion, pointing to limited standardized clinical trials, inconsistency in diagnostic frameworks, and difficulties in evidence-based validation. Moreover, commercial packaging of Ayurvedic products can marginalize traditional knowledge holders, turning living traditions into market commodities. The relationship between these systems and modern healthcare is therefore both hopeful and complex. Integrative models—especially in chronic care, mental health, and palliative support—may work, but they require epistemic humility and strict regulation. The risk lies in either glorifying these traditions as cure-alls or dismissing them as unscientific leftovers. Their future relevance depends on preserving philosophical depth while applying transparent, rigorous scrutiny, through dialogue rather than extremes.`;

export const paper17Sep: QuestionData[] = [
  // ===== PART A: General Intelligence and Reasoning (Q.1-Q.25) =====
  {
    questionNo: 1,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "P is the sister of Q. R is the father of Q. How is R related to P?",
    options: [
      { label: "A", text: "Father" },
      { label: "B", text: "Uncle" },
      { label: "C", text: "Brother" },
      { label: "D", text: "Grandfather" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 2,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out:",
    options: [
      { label: "A", text: "Copper" },
      { label: "B", text: "Iron" },
      { label: "C", text: "Gold" },
      { label: "D", text: "Plastic" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 3,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "A 20 L mixture contains milk and water in the ratio 2:3. How much milk must be added to make the ratio 4:3?",
    options: [
      { label: "A", text: "10 L" },
      { label: "B", text: "8 L" },
      { label: "C", text: "5 L" },
      { label: "D", text: "9 L" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 4,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If + = ×, − = ÷, × = +, ÷ = −, then find:\n24 + 6 − 2 × 4 ÷ 2 = ?",
    options: [
      { label: "A", text: "76" },
      { label: "B", text: "72" },
      { label: "C", text: "78" },
      { label: "D", text: "74" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 5,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series.\nCFG, EHI, GJK, ILM, ?",
    options: [
      { label: "A", text: "KNO" },
      { label: "B", text: "JMN" },
      { label: "C", text: "JMO" },
      { label: "D", text: "KMN" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 6,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following is/are identical to the address given?\nRohit Kumar, Flat 12A, Sunrise Apartments, Andheri East, Mumbai - 400069\n\n1. Rohit Kumar, Flat 12A, Sunrise Apartments, Andheri East, Mumbai - 400069\n2. Rohit Kumar, Flat 12A, Sunrise Apartments, Andheri East, Mumbai - 400069\n3. Rohit Kumar, Flat 12-A, Sunrise Apartments, Andheri East, Mumbai - 400069\n4. Rohit Kumar, Flat 12A, Sunrise Apartment, Andheri East, Mumbai - 400069",
    options: [
      { label: "A", text: "1 and 2" },
      { label: "B", text: "1 and 3" },
      { label: "C", text: "2 and 4" },
      { label: "D", text: "3 and 4" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 7,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If '+' means '×', '−' means '+', '×' means '+' and '÷' means '−'. Find the value of:\n10 ÷ 4 + 6 × 32 − 8 = ?",
    options: [
      { label: "A", text: "−6" },
      { label: "B", text: "−8" },
      { label: "C", text: "−10" },
      { label: "D", text: "−12" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 8,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "The following equation is correct. Which two signs should be interchanged to correct it?\n24 − 6 ÷ 3 × 2 + 4 = 24",
    options: [
      { label: "A", text: "− and ÷" },
      { label: "B", text: "× and +" },
      { label: "C", text: "÷ and ×" },
      { label: "D", text: "− and +" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 9,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "ROADMAP is to ORADPAM as JOURNEY is to:",
    options: [
      { label: "A", text: "OJURYEN" },
      { label: "B", text: "UOJRNEY" },
      { label: "C", text: "JUORNEY" },
      { label: "D", text: "OJURNEY" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 10,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 3 # 2 = 13, 4 # 3 = 25, then 5 # 4 = ?",
    options: [
      { label: "A", text: "39" },
      { label: "B", text: "41" },
      { label: "C", text: "43" },
      { label: "D", text: "45" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 11,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Statements: A > B = C, D ≤ E < B, F > A.\nConclusions:\nI. F > C\nII. D < A",
    options: [
      { label: "A", text: "Only I is true" },
      { label: "B", text: "Only II is true" },
      { label: "C", text: "Both I and II are true" },
      { label: "D", text: "Neither I nor II is true" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 12,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Rearrange the letters to form the name of a fruit:",
    options: [
      { label: "A", text: "lpeap" },
      { label: "B", text: "appel" },
      { label: "C", text: "paple" },
      { label: "D", text: "apple" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 13,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Statement: The price of petrol has increased.\nConclusions:\nI. Transportation costs may rise.\nII. People will stop using vehicles.",
    options: [
      { label: "A", text: "Only I follows" },
      { label: "B", text: "Only II follows" },
      { label: "C", text: "Both follow" },
      { label: "D", text: "Neither follows" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 14,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Statement: Online education provides flexibility but requires reliable internet access.\nAssumptions:\nI. Students have access to the internet.\nII. Flexibility improves learning outcomes.\nIII. Internet connectivity is essential for online education.",
    options: [
      { label: "A", text: "Only I and III are implicit" },
      { label: "B", text: "Only II and III are implicit" },
      { label: "C", text: "Only I is implicit" },
      { label: "D", text: "All are implicit" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 15,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Pointing to a girl, a woman said, \"She is the daughter of my brother's wife.\" How is the girl related to the woman?",
    options: [
      { label: "A", text: "Mother" },
      { label: "B", text: "Niece" },
      { label: "C", text: "Sister" },
      { label: "D", text: "Cousin" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 16,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Identify the relation between Statement I and Statement II.\nStatement I: The company's sales increased this year.\nStatement II: The company expanded its distribution network.",
    options: [
      { label: "A", text: "I is the cause II is the effect" },
      { label: "B", text: "II is the cause and I is the effect" },
      { label: "C", text: "Both are independent" },
      { label: "D", text: "No relation" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 17,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What will come at the place of question mark?\n7, 13, 25, 49, ?",
    options: [
      { label: "A", text: "95" },
      { label: "B", text: "97" },
      { label: "C", text: "99" },
      { label: "D", text: "101" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 18,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 20% of a number is 40, what is the number?",
    options: [
      { label: "A", text: "160" },
      { label: "B", text: "180" },
      { label: "C", text: "200" },
      { label: "D", text: "240" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 19,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Choose the address that is the same as the one given below.\nNo. 21, Green Park Residency, Bhopal, Madhya Pradesh - 462001",
    options: [
      { label: "A", text: "No. 21, Green Park Residency, Bhopal, MP - 462001" },
      { label: "B", text: "No. 21, Green Park Residency, Bhopal, Madhya Pradesh - 462001" },
      { label: "C", text: "No. 12, Green Park Residency, Bhopal, Madhya Pradesh - 462001" },
      { label: "D", text: "No. 21, Green Park Residency, Indore, Madhya Pradesh - 462001" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 20,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 7 * 2 = 98 and 9 * 3 = 243, then 5 * 4 = ?",
    options: [
      { label: "A", text: "100" },
      { label: "B", text: "120" },
      { label: "C", text: "125" },
      { label: "D", text: "140" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 21,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What comes next?\n2, 4, 12, 48, ?",
    options: [
      { label: "A", text: "230" },
      { label: "B", text: "240" },
      { label: "C", text: "220" },
      { label: "D", text: "384" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 22,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Statement: Crime rates decreased after better street lighting.\nConclusions:\nI. Visibility reduces crime.\nII. Criminals prefer darkness.",
    options: [
      { label: "A", text: "Only I follows" },
      { label: "B", text: "Only II follows" },
      { label: "C", text: "Both follow" },
      { label: "D", text: "Neither follows" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 23,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If CAT is coded as BZS, how is DOG coded?",
    options: [
      { label: "A", text: "CNF" },
      { label: "B", text: "CPF" },
      { label: "C", text: "DNF" },
      { label: "D", text: "BNF" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 24,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What comes next?\nBDF, EGI, HJL, ?",
    options: [
      { label: "A", text: "LNP" },
      { label: "B", text: "KNO" },
      { label: "C", text: "MPR" },
      { label: "D", text: "KMO" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 25,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out: Mahatma Gandhi, Subhash Chandra Bose, Jawaharlal Nehru, Bhagat Singh, Rani Lakshmibai",
    options: [
      { label: "A", text: "Mahatma Gandhi" },
      { label: "B", text: "Subhash Chandra Bose" },
      { label: "C", text: "Jawaharlal Nehru" },
      { label: "D", text: "Bhagat Singh" },
    ],
    correctOption: "C",
  },

  // ===== PART B: General Awareness (Q.26-Q.50) =====
  {
    questionNo: 26,
    part: "B",
    partName: "General Awareness",
    questionText: "Which dynasty is credited with early fortifications around the Delhi region before the Sultanate period?",
    options: [
      { label: "A", text: "Paramaras" },
      { label: "B", text: "Chahamanas" },
      { label: "C", text: "Tomaras" },
      { label: "D", text: "Palas" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 27,
    part: "B",
    partName: "General Awareness",
    questionText: "In Hindustani music, the term describing the permitted notes and their sequence in a raga is:",
    options: [
      { label: "A", text: "Tala" },
      { label: "B", text: "Bandish" },
      { label: "C", text: "Aroha-Avaroha" },
      { label: "D", text: "Laya" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 28,
    part: "B",
    partName: "General Awareness",
    questionText: "The Green Revolution in India mainly focused on:",
    options: [
      { label: "A", text: "Pulses" },
      { label: "B", text: "Oilseeds" },
      { label: "C", text: "Wheat and rice" },
      { label: "D", text: "Cotton" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 29,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the following statements about the Hubble Space Telescope (HST):\n1. It operates mainly in the visible, ultraviolet, and near-infrared wavelengths.\n2. It is placed in a geostationary orbit above the Earth.\n3. It has contributed to measuring the rate of expansion of the Universe.\nWhich of the above statements is/are correct?",
    options: [
      { label: "A", text: "Only 1 and 2" },
      { label: "B", text: "Only 1 and 3" },
      { label: "C", text: "Only 2 and 3" },
      { label: "D", text: "All 1, 2 and 3" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 30,
    part: "B",
    partName: "General Awareness",
    questionText: "Statement 1: Inflation reduces purchasing power.\nStatement 2: Inflation always benefits savers.",
    options: [
      { label: "A", text: "Only Statement 1 is correct" },
      { label: "B", text: "Only Statement 2 is correct" },
      { label: "C", text: "Both are correct" },
      { label: "D", text: "Neither is correct" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 31,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the following statements about photosynthesis:\n1. Chlorophyll absorbs light energy.\n2. It occurs only at night.\n3. Oxygen is released as a by-product.\nWhich are correct?",
    options: [
      { label: "A", text: "1 and 3 only" },
      { label: "B", text: "2 and 3 only" },
      { label: "C", text: "1 only" },
      { label: "D", text: "1, 2 and 3" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 32,
    part: "B",
    partName: "General Awareness",
    questionText: "Assertion (A): GST created a unified tax system.\nReason (R): It replaced multiple indirect taxes.",
    options: [
      { label: "A", text: "Both A and R are true and R explains A" },
      { label: "B", text: "Both true but R not explanation" },
      { label: "C", text: "A true, R false" },
      { label: "D", text: "A false, R true" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 33,
    part: "B",
    partName: "General Awareness",
    questionText: "Liberalisation refers to:",
    options: [
      { label: "A", text: "Increased government control" },
      { label: "B", text: "Reduction of trade barriers" },
      { label: "C", text: "Nationalisation" },
      { label: "D", text: "Currency demonetisation" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 34,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following pairs is correctly matched?",
    options: [
      { label: "A", text: "Wood's Despatch — Promotion of English education system" },
      { label: "B", text: "Hunter Commission — Abolition of universities" },
      { label: "C", text: "Sadler Commission — Focus on primary schooling only" },
      { label: "D", text: "Raleigh Commission — Vernacular press control" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 35,
    part: "B",
    partName: "General Awareness",
    questionText: "The Human Development Index mainly considers:",
    options: [
      { label: "A", text: "Income, health, and education" },
      { label: "B", text: "Population growth" },
      { label: "C", text: "Inflation rate" },
      { label: "D", text: "Export levels" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 36,
    part: "B",
    partName: "General Awareness",
    questionText: "Match the dance with state:\n1. Bhangra — A. Gujarat\n2. Garba — B. Punjab\n3. Lavani — C. Maharashtra\n4. Yakshagana — D. Karnataka",
    options: [
      { label: "A", text: "1-B, 2-A, 3-C, 4-D" },
      { label: "B", text: "1-A, 2-B, 3-D, 4-C" },
      { label: "C", text: "1-B, 2-C, 3-A, 4-D" },
      { label: "D", text: "1-D, 2-A, 3-B, 4-C" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 37,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the following statements about the Fifth Schedule of the Indian Constitution:\n1. It deals with the administration and control of Scheduled Areas and Scheduled Tribes.\n2. The Governor of a state with Scheduled Areas can issue regulations to restrict land transfer from tribals to non-tribals.\nWhich of the above statements is/are correct?",
    options: [
      { label: "A", text: "Only 1" },
      { label: "B", text: "Only 2" },
      { label: "C", text: "Both 1 and 2" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 38,
    part: "B",
    partName: "General Awareness",
    questionText: "Perini Shivatandavam, a vigorous dance tradition associated with warrior rituals and later revived in the 20th century by Nataraja Ramakrishna, is primarily linked to which Indian state?",
    options: [
      { label: "A", text: "Odisha" },
      { label: "B", text: "Telangana" },
      { label: "C", text: "Tamil Nadu" },
      { label: "D", text: "Karnataka" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 39,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the following statements carefully:\nStatement 1: The dockyard at Lothal indicates maritime trade activity.\nStatement 2: Harappans used standardized weights for commerce.\nWhich of the following is/are correct?",
    options: [
      { label: "A", text: "Only S1" },
      { label: "B", text: "Only S2" },
      { label: "C", text: "Both S1 and S2 are correct" },
      { label: "D", text: "Neither S1 nor S2 is correct" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 40,
    part: "B",
    partName: "General Awareness",
    questionText: "The annual cultural festival that showcases the traditions of multiple Naga tribes is organized to coincide with the Statehood Day of Nagaland. This festival is scheduled every year beginning on which date?",
    options: [
      { label: "A", text: "1 December" },
      { label: "B", text: "15 January" },
      { label: "C", text: "26 November" },
      { label: "D", text: "5 March" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 41,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Article deals with the President's ordinance-making power?",
    options: [
      { label: "A", text: "Article 110" },
      { label: "B", text: "Article 123" },
      { label: "C", text: "Article 356" },
      { label: "D", text: "Article 368" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 42,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following initiatives focuses on enhancing climate resilience in drought-prone regions through integrated watershed management and community participation?",
    options: [
      { label: "A", text: "National Afforestation Programme" },
      { label: "B", text: "Integrated Watershed Management Programme" },
      { label: "C", text: "Green India Mission" },
      { label: "D", text: "Desert Development Scheme" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 43,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Mughal structure is known for its extensive use of red sandstone combined with white marble decoration?",
    options: [
      { label: "A", text: "Jama Masjid, Delhi" },
      { label: "B", text: "Agra Fort" },
      { label: "C", text: "Bibi Ka Maqbara" },
      { label: "D", text: "Moti Masjid" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 44,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following statements about the Asian Games is/are correct?\n1. They are regulated by the Olympic Council of Asia.\n2. They are held every four years.",
    options: [
      { label: "A", text: "Only 1" },
      { label: "B", text: "Only 2" },
      { label: "C", text: "Both 1 and 2 are correct" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 45,
    part: "B",
    partName: "General Awareness",
    questionText: "India's first individual Olympic gold medal in athletics was won in:",
    options: [
      { label: "A", text: "Tokyo Olympics" },
      { label: "B", text: "Rio Olympics" },
      { label: "C", text: "Paris Olympics" },
      { label: "D", text: "Beijing Olympics" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 46,
    part: "B",
    partName: "General Awareness",
    questionText: "In athletics, the term \"foul line\" is commonly associated with:",
    options: [
      { label: "A", text: "High jump" },
      { label: "B", text: "Shot put" },
      { label: "C", text: "Marathon" },
      { label: "D", text: "Hurdles" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 47,
    part: "B",
    partName: "General Awareness",
    questionText: "The National Games 2022 in India were hosted by:",
    options: [
      { label: "A", text: "Kerala" },
      { label: "B", text: "Maharashtra" },
      { label: "C", text: "Gujarat" },
      { label: "D", text: "Punjab" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 48,
    part: "B",
    partName: "General Awareness",
    questionText: "Who authored the book \"Ignited Minds\"?",
    options: [
      { label: "A", text: "R. Narayan" },
      { label: "B", text: "A.P.J. Abdul Kalam" },
      { label: "C", text: "Vikram Seth" },
      { label: "D", text: "Amartya Sen" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 49,
    part: "B",
    partName: "General Awareness",
    questionText: "Minimum age to become a member of Rajya Sabha is:",
    options: [
      { label: "A", text: "25" },
      { label: "B", text: "30" },
      { label: "C", text: "35" },
      { label: "D", text: "40" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 50,
    part: "B",
    partName: "General Awareness",
    questionText: "India and Bhutan mainly coordinate on hydropower development and management of shared river systems through which bilateral arrangement?",
    options: [
      { label: "A", text: "India–Bhutan Energy Dialogue" },
      { label: "B", text: "Joint Group of Experts on Hydropower" },
      { label: "C", text: "South Asian Power Pool" },
      { label: "D", text: "Himalayan River Commission" },
    ],
    correctOption: "B",
  },

  // ===== PART C: Quantitative Aptitude (Q.51-Q.75) =====
  {
    questionNo: 51,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The area of a triangle is 25 cm². If a similar triangle has sides three times the corresponding sides of the first triangle, find its area.",
    options: [
      { label: "A", text: "75 cm²" },
      { label: "B", text: "150 cm²" },
      { label: "C", text: "225 cm²" },
      { label: "D", text: "300 cm²" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 52,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "From an external point P, two tangents PA and PB are drawn to a circle. If the length of PA is 15 cm, find the length of PB.",
    options: [
      { label: "A", text: "10 cm" },
      { label: "B", text: "12 cm" },
      { label: "C", text: "15 cm" },
      { label: "D", text: "18 cm" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 53,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If sinA + cosA = 7/5, find sin2A.",
    options: [
      { label: "A", text: "9/25" },
      { label: "B", text: "24/25" },
      { label: "C", text: "7/10" },
      { label: "D", text: "12/25" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 54,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If A : B = 4 : 5, B : C = 6 : 7, and C : D = 10 : 11, find the compound ratio A : B : C : D.",
    options: [
      { label: "A", text: "48 : 60 : 70 : 77" },
      { label: "B", text: "4 : 5 : 7 : 11" },
      { label: "C", text: "24 : 30 : 35 : 44" },
      { label: "D", text: "8 : 10 : 14 : 11" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 55,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "27³ + 18³ − 45³ + 108 is equal to:",
    options: [
      { label: "A", text: "−65502" },
      { label: "B", text: "0" },
      { label: "C", text: "−46656" },
      { label: "D", text: "1" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 56,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A line L is the perpendicular bisector of the line segment joining points P(4, 6) and Q(10, 2). What is the y-intercept of line L?",
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "−6.5" },
      { label: "C", text: "6" },
      { label: "D", text: "7" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 57,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If the radius of a cone is doubled and its height is reduced to half, how does the volume change?",
    options: [
      { label: "A", text: "Becomes half of the original" },
      { label: "B", text: "Becomes double of the original" },
      { label: "C", text: "Remains unchanged" },
      { label: "D", text: "Becomes four times the original" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 58,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If cotA = 3, find the value of (tanA + cotA).",
    options: [
      { label: "A", text: "10/3" },
      { label: "B", text: "4/3" },
      { label: "C", text: "13/3" },
      { label: "D", text: "3/10" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 59,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "What is the minimum number of cuts required to divide a cube into 27 equal smaller cubes?",
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "5" },
      { label: "C", text: "6" },
      { label: "D", text: "3" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 60,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A triangle can have:",
    options: [
      { label: "A", text: "Two obtuse angles" },
      { label: "B", text: "One acute angle and two right angles" },
      { label: "C", text: "Only one obtuse angle" },
      { label: "D", text: "Three angles each equal to 70°" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 61,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If a = 0.01, b = 0.02, c = −0.03 and a + b + c = 0, find (a³ + b³ + c³) ÷ (3abc).",
    options: [
      { label: "A", text: "−1" },
      { label: "B", text: "0" },
      { label: "C", text: "1" },
      { label: "D", text: "2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 62,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A circle is inscribed in a right-angled triangle whose perpendicular sides are 9 cm and 12 cm. Find the radius of the inscribed circle.",
    options: [
      { label: "A", text: "2 cm" },
      { label: "B", text: "3 cm" },
      { label: "C", text: "4 cm" },
      { label: "D", text: "5 cm" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 63,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: √(17 + 12√2)",
    options: [
      { label: "A", text: "4 + √2" },
      { label: "B", text: "2 + 3√2" },
      { label: "C", text: "3 + 2√2" },
      { label: "D", text: "5 + √4" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 64,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If cosθ = 5/13 and θ lies in the first quadrant, find the value of sinθ.",
    options: [
      { label: "A", text: "12/13" },
      { label: "B", text: "5/12" },
      { label: "C", text: "13/12" },
      { label: "D", text: "12/5" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 65,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A sector of a circle subtends an angle of 90° at the centre and has radius 6 cm. Another sector of the same circle subtends an angle of π/2 radians. Find the ratio of the areas of the two sectors.",
    options: [
      { label: "A", text: "1 : 2" },
      { label: "B", text: "2 : 1" },
      { label: "C", text: "1 : 1" },
      { label: "D", text: "3 : 2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 66,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Find the value of x = √(15 + √(15 + √(15 + ⋯)))",
    options: [
      { label: "A", text: "3" },
      { label: "B", text: "2" },
      { label: "C", text: "(1 + √61)/2" },
      { label: "D", text: "4" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 67,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A shopkeeper buys 9 pens for the marked price of 8 pens. He sells each pen after allowing a discount of 5% on the marked price. Find his profit percentage.",
    options: [
      { label: "A", text: "10%" },
      { label: "B", text: "11.25%" },
      { label: "C", text: "6.875%" },
      { label: "D", text: "15%" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 68,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If x + y = 7 and xy = 10, find: (x³ + y³)² − 9x²y²(x + y)²",
    options: [
      { label: "A", text: "24011" },
      { label: "B", text: "−26411" },
      { label: "C", text: "12255" },
      { label: "D", text: "−12251" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 69,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Find the slope of the line 4x − 5y = 10.",
    options: [
      { label: "A", text: "4/5" },
      { label: "B", text: "−5/4" },
      { label: "C", text: "5/4" },
      { label: "D", text: "−4/5" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 70,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "₹800 is lent at a certain rate of simple interest. After 4 months, another ₹1200 is lent at a rate which is twice the original rate. If the total simple interest after 1 year is ₹96, find the original rate.",
    options: [
      { label: "A", text: "4%" },
      { label: "B", text: "5%" },
      { label: "C", text: "8%" },
      { label: "D", text: "7%" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 71,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A tower casts a shadow of 15 meters on the ground. If the height of the tower is 15√3 meters, find the angle of elevation of the sun.",
    options: [
      { label: "A", text: "30°" },
      { label: "B", text: "45°" },
      { label: "C", text: "60°" },
      { label: "D", text: "75°" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 72,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The volume of a hemisphere is numerically equal to three times its curved surface area. Find the radius of the hemisphere.",
    options: [
      { label: "A", text: "9 cm" },
      { label: "B", text: "10.5 cm" },
      { label: "C", text: "12 cm" },
      { label: "D", text: "14 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 73,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A sum of ₹12000 is divided into two parts and lent at 6% and 11% simple interest respectively. If the total annual interest earned is ₹960, find the amount lent at 11%.",
    options: [
      { label: "A", text: "₹5000" },
      { label: "B", text: "₹4800" },
      { label: "C", text: "₹7000" },
      { label: "D", text: "₹8000" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 74,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Pipe A can fill a tank in 18 minutes and Pipe B can fill it in 36 minutes. Both are opened together. After 6 minutes, the rate of Pipe A becomes half and Pipe B's rate becomes double. How many more minutes are required to fill the tank?",
    options: [
      { label: "A", text: "5 min" },
      { label: "B", text: "6 min" },
      { label: "C", text: "7 min" },
      { label: "D", text: "8 min" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 75,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A hollow iron sphere with an outer radius of 14 cm is melted and recast into 64 identical solid spheres, each of radius 3.5 cm. Find the inner radius (nearest integer) of the original sphere.",
    options: [
      { label: "A", text: "10 cm" },
      { label: "B", text: "11 cm" },
      { label: "C", text: "12 cm" },
      { label: "D", text: "9 cm" },
    ],
    correctOption: "A",
  },

  // ===== PART D: English Comprehension (Q.76-Q.100) =====
  {
    questionNo: 76,
    part: "D",
    partName: "English Comprehension",
    questionText: "A sentence is provided in direct speech. Choose the one that most accurately conveys the sentence in indirect speech.\nHe said to me, \"You ought to study harder.\"",
    options: [
      { label: "A", text: "He said me that I ought to study harder." },
      { label: "B", text: "He told me that I ought to study harder." },
      { label: "C", text: "He told me that you ought to study harder." },
      { label: "D", text: "He told that I ought to study harder." },
    ],
    correctOption: "B",
  },
  {
    questionNo: 77,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate synonym of the given word:\n**EXIGUOUS**",
    options: [
      { label: "A", text: "Meagre" },
      { label: "B", text: "Immense" },
      { label: "C", text: "Redundant" },
      { label: "D", text: "Plentiful" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 78,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the word that is spelled correctly and means the quality of being harshly sarcastic.",
    options: [
      { label: "A", text: "Causticity" },
      { label: "B", text: "Caustisity" },
      { label: "C", text: "Caustyciti" },
      { label: "D", text: "Costicity" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 79,
    part: "D",
    partName: "English Comprehension",
    questionText: "A sentence is provided in indirect speech. Choose the one that most accurately conveys the sentence in direct speech.\nThe envoy said that only after the truce would talks commence.",
    options: [
      { label: "A", text: "\"Talks commence only after the truce,\" said the envoy." },
      { label: "B", text: "\"Only after the truce, talks would commence,\" said the envoy." },
      { label: "C", text: "\"Only after the truce will talks commence,\" said the envoy." },
      { label: "D", text: "\"Talks would commence once the truce is declared,\" said the envoy." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 80,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word.\n**Abrogate**",
    options: [
      { label: "A", text: "Rescind" },
      { label: "B", text: "Annul" },
      { label: "C", text: "Ratify" },
      { label: "D", text: "Repeal" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 81,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitute for: \"Extremely ancient; belonging to a very remote period.\"",
    options: [
      { label: "A", text: "Antiquated" },
      { label: "B", text: "Medieval" },
      { label: "C", text: "Antediluvian" },
      { label: "D", text: "Obsolete" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 82,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate synonym of the given word:\n**LUMINOUS**",
    options: [
      { label: "A", text: "Gloomy" },
      { label: "B", text: "Murky" },
      { label: "C", text: "Opaque" },
      { label: "D", text: "Resplendent" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 83,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct meaning of idiom:\n**To chew over an idea**",
    options: [
      { label: "A", text: "Eat noisily" },
      { label: "B", text: "Wander aimlessly in thought" },
      { label: "C", text: "Think deeply and repeatedly" },
      { label: "D", text: "Prepare aggressively for conflict" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 84,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitute for: \"A person who advocates reform or improvement.\"",
    options: [
      { label: "A", text: "Traditionalist" },
      { label: "B", text: "Reactionary" },
      { label: "C", text: "Reformer" },
      { label: "D", text: "Absolutist" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 85,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences in correct order to make a logical passage.\n1. The plan is approved after consent from all partners.\n2. First, a preliminary outline is drafted.\n3. Then modifications are made after consultations.\n4. Finally, implementation starts according to schedule.",
    options: [
      { label: "A", text: "2-3-1-4" },
      { label: "B", text: "1-3-2-4" },
      { label: "C", text: "3-2-1-4" },
      { label: "D", text: "2-1-3-4" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 86,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. A core concept in this paradigm is the \"class,\" which serves as a template for creating objects.\n2. Object-Oriented Programming (OOP) is a paradigm built around \"objects,\" which contain data as well as methods.\n3. This enables a developer to define the structure and behavior of programs in an object-based manner.\n4. A key benefit is that it mirrors real-world entities, making large systems easier to maintain and debug.",
    options: [
      { label: "A", text: "2, 1, 3, 4" },
      { label: "B", text: "4, 3, 2, 1" },
      { label: "C", text: "3, 1, 4, 2" },
      { label: "D", text: "1, 2, 3, 4" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 87,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nSeldom had the tribunal entertained an appeal (1)/ so lacking in substance, nor so plainly designed (2)/ to invite publicity rather than justice. (3)/ No error (4)/",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 88,
    part: "D",
    partName: "English Comprehension",
    questionText: "Change the following from active to passive:\nThey were broadcasting the match at 8 pm.",
    options: [
      { label: "A", text: "The match is broadcast at 8 pm." },
      { label: "B", text: "The match was broadcast at 8 pm." },
      { label: "C", text: "The match was being broadcast at 8 pm." },
      { label: "D", text: "The match has been broadcast at 8 pm." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 89,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct option:\nThe sociologist's conclusions were so contentious that they were initially _____.",
    options: [
      { label: "A", text: "dismissed" },
      { label: "B", text: "applauded" },
      { label: "C", text: "endorsed" },
      { label: "D", text: "implemented" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 90,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nThe revised guideline states (1)/ that every employee must comply with (2)/ the conduct policy (3)/ regardless of their designation. (4)/",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 91,
    part: "D",
    partName: "English Comprehension",
    questionText: "Convert the sentence from passive voice to active voice:\nA decision has been made to get the manuscript reviewed by an external committee.",
    options: [
      { label: "A", text: "An external committee has reviewed the manuscript." },
      { label: "B", text: "The manuscript is being reviewed by an external committee." },
      { label: "C", text: "They have decided to get the manuscript reviewed by an external committee." },
      { label: "D", text: "The manuscript was reviewed by the committee as per the decision." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 92,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nShe is confident **to clear** the interview.",
    options: [
      { label: "A", text: "of to clear" },
      { label: "B", text: "that she clears" },
      { label: "C", text: "of clearing the interview" },
      { label: "D", text: "on clearing interview" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 93,
    part: "D",
    partName: "English Comprehension",
    questionText: "What concern does the passage raise about Yoga's worldwide popularity?",
    options: [
      { label: "A", text: "Lack of studios" },
      { label: "B", text: "Dilution of its philosophical foundation" },
      { label: "C", text: "Shortage of practitioners" },
      { label: "D", text: "Excess control by Indian agencies" },
    ],
    correctOption: "B",
    passage: PASSAGE_YOGA_AYURVEDA,
  },
  {
    questionNo: 94,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which option best represents the Ayurvedic view of illness, as discussed in the passage?",
    options: [
      { label: "A", text: "Destroying pathogens through antibiotics" },
      { label: "B", text: "Using synthetic drugs for instant relief" },
      { label: "C", text: "Rebalancing the body through lifestyle and routine" },
      { label: "D", text: "Correcting genetic defects directly" },
    ],
    correctOption: "C",
    passage: PASSAGE_YOGA_AYURVEDA,
  },
  {
    questionNo: 95,
    part: "D",
    partName: "English Comprehension",
    questionText: "What risk linked to institutional promotion of AYUSH is mentioned in the passage?",
    options: [
      { label: "A", text: "Rising production costs" },
      { label: "B", text: "Increased rural joblessness" },
      { label: "C", text: "Traditional knowledge holders being sidelined" },
      { label: "D", text: "Dependence on foreign investors" },
    ],
    correctOption: "C",
    passage: PASSAGE_YOGA_AYURVEDA,
  },
  {
    questionNo: 96,
    part: "D",
    partName: "English Comprehension",
    questionText: "What position does the author take regarding combining traditional medicine with modern healthcare?",
    options: [
      { label: "A", text: "Traditional systems should replace allopathy" },
      { label: "B", text: "Modern medicine must reject tradition" },
      { label: "C", text: "Integration can work with humility and regulation" },
      { label: "D", text: "Both should remain strictly separate" },
    ],
    correctOption: "C",
    passage: PASSAGE_YOGA_AYURVEDA,
  },
  {
    questionNo: 97,
    part: "D",
    partName: "English Comprehension",
    questionText: "According to the passage, what is essential for the continued relevance of Yoga and traditional medicine in India?",
    options: [
      { label: "A", text: "Unquestioning patriotism" },
      { label: "B", text: "Complete scientific dismissal" },
      { label: "C", text: "A dialogic integration of tradition and modernity" },
      { label: "D", text: "Reliance only on foreign approval" },
    ],
    correctOption: "C",
    passage: PASSAGE_YOGA_AYURVEDA,
  },
  {
    questionNo: 98,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct spelling of a word meaning \"light, witty talk or banter.\"",
    options: [
      { label: "A", text: "Persiflage" },
      { label: "B", text: "Persiflaige" },
      { label: "C", text: "Persiphlege" },
      { label: "D", text: "Persiflagee" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 99,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the option that most accurately conveys the sentence in indirect speech.\nThe researcher said, \"We have been observing this phenomenon for months.\"",
    options: [
      { label: "A", text: "The researcher said they had been observing that phenomenon for months." },
      { label: "B", text: "The researcher said they have been observing this phenomenon for months." },
      { label: "C", text: "The researcher said that they were observing that phenomenon." },
      { label: "D", text: "The researcher said that we had observed this phenomenon." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 100,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the sentence containing the homonym of the highlighted word:\nThe bishop denounced the act as **simony**, citing church law.",
    options: [
      { label: "A", text: "The cleric was charged with simony for selling sacred offices." },
      { label: "B", text: "Historians noted that simony corrupted many medieval appointments." },
      { label: "C", text: "The chemist measured the simony of the compound under pressure." },
      { label: "D", text: "Simony was condemned repeatedly by reform councils." },
    ],
    correctOption: "C",
  },
];
