export interface QuestionData {
  questionNo: number;
  part: string;
  partName: string;
  questionText: string;
  options: { label: string; text: string }[];
  correctOption: string;
  passage?: string;
}

const PASSAGE_90_94 = `While education and wisdom are often conflated in colloquial discourse, a discerning mind perceives a fundamental divergence between the two. Education is the formal acquisition of knowledge, often measured through degrees, academic accolades, and proficiency in structured disciplines. It is delivered through systematic curricula, institutionalized assessment, and theoretical frameworks. However, wisdom transcends this rigidity; it is the judicious application of knowledge to real-life contexts, enriched by experience, introspection, and emotional intelligence. An individual may be extensively educated yet remain bereft of wisdom if they lack the discernment to apply their learning ethically and effectively. Conversely, many wise individuals—farmers, artisans, elders—may not possess formal education, but their decisions exhibit prudence and sagacity cultivated through lived realities. Thus, education equips the mind, but wisdom enriches the soul. In an era dominated by information overload and algorithmic thinking, the schism between the two has widened. Educational institutions often prioritize rote memorization and standardized testing over critical thinking and moral reasoning. Consequently, society produces individuals proficient in problem-solving but deficient in decision-making that requires empathy, patience, or foresight. Wisdom, being innately human, cannot be downloaded or fast-tracked; it is earned through trial, failure, reflection, and a nuanced understanding of human nature. Furthermore, while education is temporally bounded—ending with formal schooling or academic milestones—wisdom is a lifelong pursuit. It does not boast certificates but manifests in humility, ethical consistency, and the ability to navigate ambiguity with grace. Ultimately, the highest form of intelligence lies not merely in knowing what is right, but in consistently choosing to do it, especially when it is inconvenient.`;

export const questionsData: QuestionData[] = [
  // ===== PART A: General Intelligence and Reasoning (Q.1-Q.25) =====
  {
    questionNo: 1,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In the following question, select the related word from the given alternatives.\nWatt : Power :: Pascal : ?",
    options: [
      { label: "A", text: "Energy" },
      { label: "B", text: "Temperature" },
      { label: "C", text: "Pressure" },
      { label: "D", text: "Force" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 2,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In the following question, select the related word from the given alternatives.\nMekong : Tibet :: Amazon : ?",
    options: [
      { label: "A", text: "Chile" },
      { label: "B", text: "Peru" },
      { label: "C", text: "Colombia" },
      { label: "D", text: "Ecuador" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 3,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series.\nC G K, G K O, K O S, O S W, ?",
    options: [
      { label: "A", text: "SDA" },
      { label: "B", text: "KNB" },
      { label: "C", text: "SWA" },
      { label: "D", text: "KJH" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 4,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series.\nMIN, NJM, OKL, PLK, ?",
    options: [
      { label: "A", text: "QWS" },
      { label: "B", text: "HGF" },
      { label: "C", text: "QMJ" },
      { label: "D", text: "UJH" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 5,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series.\nBRF, EUH, HXJ, KAL, ?",
    options: [
      { label: "A", text: "NMB" },
      { label: "B", text: "NKH" },
      { label: "C", text: "NHG" },
      { label: "D", text: "NDN" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 6,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series.\nWZWT, WVOH, WRGV, WNYJ, ?",
    options: [
      { label: "A", text: "WJQX" },
      { label: "B", text: "WJQW" },
      { label: "C", text: "WHPX" },
      { label: "D", text: "WJPX" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 7,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series.\nMCFI, NEKP, OGPW, PIUD, ?",
    options: [
      { label: "A", text: "NKYD" },
      { label: "B", text: "QLYL" },
      { label: "C", text: "QKZK" },
      { label: "D", text: "QKZL" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 8,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What comes next: 3, 12, 7, 16, 11, 20, 15, ?",
    options: [
      { label: "A", text: "16" },
      { label: "B", text: "24" },
      { label: "C", text: "14" },
      { label: "D", text: "18" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 9,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Each of the letters in the word STUDENT is arranged in alphabetical order. How many letters are there in the English alphabetical series between the letter that is second from the left and the one that is fourth from the right in the new letter-cluster formed?",
    options: [
      { label: "A", text: "17" },
      { label: "B", text: "13" },
      { label: "C", text: "11" },
      { label: "D", text: "15" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 10,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following addresses are identical to each other:\n1. Arjun Mehta A-101, Emerald Towers, Surat, 395001\n2. Arjun Mehta A-101, Emerald Tower, Surat, 395001\n3. Arjun M. A-101, Emerald Tower, Surat, 395001\n4. Arjun Mehta A-101, Emerald Tower, Surat, 395001",
    options: [
      { label: "A", text: "1 and 2" },
      { label: "B", text: "1 and 3" },
      { label: "C", text: "2 and 4" },
      { label: "D", text: "3 and 4" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 11,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following is/are identical to the address given: Meenal Gupta 102, Silver Oaks, Sector 12, Noida, 201301\n1. Meenal Gupta 102, Silver Oaks, Sector 12, Noida, 201301\n2. Meenal Gupta 102, Silver Oaks, Sector-12, Noida, 201301\n3. Meenal Gupta 102, Silver Oaks, Sector 12, Noida 201301\n4. Meenal Gupta 102, Silver Oaks, Sector 12, Noida, 201302",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "3" },
      { label: "C", text: "2" },
      { label: "D", text: "4" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 12,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the option that best completes the analogy.\nAG : IO :: CM : ?",
    options: [
      { label: "A", text: "KO" },
      { label: "B", text: "KU" },
      { label: "C", text: "KS" },
      { label: "D", text: "KW" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 13,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "A is facing North. B is seated second to the right of A. Who is sitting immediately to the left of B?",
    options: [
      { label: "A", text: "The person seated to the immediate right of A" },
      { label: "B", text: "The person seated opposite to A" },
      { label: "C", text: "The person seated to the immediate left of A" },
      { label: "D", text: "Cannot be determined" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 14,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In the following question, the second word is related to the first word by a specific pattern of letter transformation. Identify the same pattern and apply it to the third word to find the correct option that completes the analogy.\nTIME : VJOG :: WORD : ?",
    options: [
      { label: "A", text: "YPTF" },
      { label: "B", text: "YQTG" },
      { label: "C", text: "YPSF" },
      { label: "D", text: "ZPSF" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 15,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In each of the following questions, a specific pattern such as reversal or rearrangement has been applied to the first word to get the second. Apply the same pattern to the third word and find the correct answer from the given options.\nGNIDAER : READING :: NOITULOS : ?",
    options: [
      { label: "A", text: "SOLUTION" },
      { label: "B", text: "SOLUNOIT" },
      { label: "C", text: "NOILOSUT" },
      { label: "D", text: "POLLUTION" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 16,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In each of the following questions, the first word is coded to form the second word using a specific rearrangement and/or substitution rule. Apply the same rule to the third word to determine the correct corresponding word from the given alternatives.\nAYRRJC : CATTLE :: NCPDCAR : ?",
    options: [
      { label: "A", text: "SUBJECTS" },
      { label: "B", text: "NEGLECT" },
      { label: "C", text: "PERFECT" },
      { label: "D", text: "OPERATE" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 17,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Identify the odd one: 2, 3, 5, 7, 11, 13, 17, 20",
    options: [
      { label: "A", text: "17" },
      { label: "B", text: "13" },
      { label: "C", text: "20" },
      { label: "D", text: "11" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 18,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following is the odd one out?",
    options: [
      { label: "A", text: "2, 3, 5" },
      { label: "B", text: "11, 13, 17" },
      { label: "C", text: "4, 6, 8" },
      { label: "D", text: "7, 19, 23" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 19,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Rani said, "The man in the photo is my mother\'s son-in-law." Who is the man to Rani?',
    options: [
      { label: "A", text: "Husband" },
      { label: "B", text: "Father" },
      { label: "C", text: "Uncle" },
      { label: "D", text: "Cousin" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 20,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In each of the following questions, a group of three numbers/symbols is given in each option. Identify the group that does NOT follow the same pattern as the others.",
    options: [
      { label: "A", text: "K11 : I9 : G7" },
      { label: "B", text: "M13 : K11 : I9" },
      { label: "C", text: "O15 : M13 : K11" },
      { label: "D", text: "N14 : K11 : H8" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 21,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In each of the following questions, a group of three numbers/symbols is given in each option. Identify the group that does NOT follow the same pattern as the others.",
    options: [
      { label: "A", text: "A1@ : B2# : C3$" },
      { label: "B", text: "D4% : E5^ : F6&" },
      { label: "C", text: "G7* : H8( : I9)" },
      { label: "D", text: "J10_ : K11@ : L12@" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 22,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Pointing to a man, a woman said, "His mother is the only daughter of my father." How is the man related to the woman?',
    options: [
      { label: "A", text: "Son" },
      { label: "B", text: "Nephew" },
      { label: "C", text: "Cousin" },
      { label: "D", text: "Grandson" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 23,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Pointing to a woman, John says, "She is the wife of my uncle\'s only son." How is the woman related to John?',
    options: [
      { label: "A", text: "Sister" },
      { label: "B", text: "Cousin" },
      { label: "C", text: "Sister-in-law" },
      { label: "D", text: "Niece" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 24,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: '"My mother\'s husband\'s only son is the father of your sister\'s brother." How is the man related to you?',
    options: [
      { label: "A", text: "Uncle" },
      { label: "B", text: "Father" },
      { label: "C", text: "Grandfather" },
      { label: "D", text: "Brother" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 25,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If # = ×, @ = −, $ = +, then evaluate: 9 # 2 @ 3 $ 1",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "14" },
      { label: "C", text: "16" },
      { label: "D", text: "17" },
    ],
    correctOption: "C",
  },

  // ===== PART B: General Awareness (Q.26-Q.50) =====
  {
    questionNo: 26,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following features distinguishes the Elephanta Caves from other rock-cut sites of early India?",
    options: [
      { label: "A", text: "They are primarily Buddhist caves with large stupas." },
      { label: "B", text: "The caves focus on Shaivite themes and feature sculptural depth through light and shadow." },
      { label: "C", text: "They contain a mix of Jain and Vaishnavite depictions in pillar halls." },
      { label: "D", text: "The caves are entirely monolithic structures from the Mauryan period." },
    ],
    correctOption: "B",
  },
  {
    questionNo: 27,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the statements about the Goncha Festival of Bastar:\n1. Tupki, a mock gun made of bamboo, uses Goncha fruit as bullets.\n2. The chariot procession was started by Chalukya rulers.\n3. Rath Yatra begins on Ashadh Shukla Dashmi and ends on Dutiya.\nWhich of the above statements are correct?",
    options: [
      { label: "A", text: "Only 1 and 2" },
      { label: "B", text: "Only 2 and 3" },
      { label: "C", text: "Only 1 and 3" },
      { label: "D", text: "1, 2 and 3 are correct" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 28,
    part: "B",
    partName: "General Awareness",
    questionText: "Fill in the blanks: In Carnatic music, a laghu with five beats is known as ___ jaati.",
    options: [
      { label: "A", text: "Tishra" },
      { label: "B", text: "Chaturashra" },
      { label: "C", text: "Khanda" },
      { label: "D", text: "Mishra" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 29,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following statements about Judo is correct?",
    options: [
      { label: "A", text: "Judo was introduced in 1882 by Jigoro Kano in Japan." },
      { label: "B", text: "India's first National Judo Championship was held in 1970 at Delhi University." },
      { label: "C", text: "Kalpana Devi won gold at the 2010 Judo World Cup." },
      { label: "D", text: "Judo became an Olympic sport in 1965." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 30,
    part: "B",
    partName: "General Awareness",
    questionText: "Where and when will the 59th National Cross Country Championships – 2025 be held?",
    options: [
      { label: "A", text: "10th January 2025, Lucknow, Uttar Pradesh" },
      { label: "B", text: "12th January 2025, Meerut, Uttar Pradesh" },
      { label: "C", text: "15th January 2025, Kanpur, Uttar Pradesh" },
      { label: "D", text: "12th January 2025, Jaipur, Rajasthan" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 31,
    part: "B",
    partName: "General Awareness",
    questionText: "What is the core structural focus of the 2024 India–UAE Bilateral Investment Treaty (BIT) within India's international investment strategy?",
    options: [
      { label: "A", text: "Proposes joint sovereign funds and links INR swap with UAE banks." },
      { label: "B", text: "Focuses on pre-establishment rights and UAE-based arbitration." },
      { label: "C", text: "Assures post-establishment investor confidence via standard and national treatment." },
      { label: "D", text: "Aims at GCC-wide tax regulation under India-led digital framework." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 32,
    part: "B",
    partName: "General Awareness",
    questionText: "Fill in the blanks: The Santosh Trophy 2022–23 final was uniquely held in _____, where Karnataka defeated Meghalaya to win the title after 54 years.",
    options: [
      { label: "A", text: "Dubai" },
      { label: "B", text: "Riyadh" },
      { label: "C", text: "Doha" },
      { label: "D", text: "Muscat" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 33,
    part: "B",
    partName: "General Awareness",
    questionText: 'Which of the following statements best captures the essence of "Landscapes of Loss: The Story of an Indian Drought" by Kavitha Iyer?',
    options: [
      { label: "A", text: "A study on drought's human and ecological impacts in India." },
      { label: "B", text: "A fictional story about a family in a drought-hit area." },
      { label: "C", text: "A history of monsoon patterns and ancient agriculture in India." },
      { label: "D", text: "A colonial-era policy analysis of water management." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 34,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the following statements about glacial landforms:\nStatement 1: Hanging valleys are often found opening into main glacial valleys at higher elevations.\nStatement 2: Spurs of such hanging valleys are frequently truncated into triangular facets.\nWhich of the following Statements is/are Correct?",
    options: [
      { label: "A", text: "Only 1" },
      { label: "B", text: "Only 2" },
      { label: "C", text: "1 and 2 are correct" },
      { label: "D", text: "Neither 1 nor 2 are correct" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 35,
    part: "B",
    partName: "General Awareness",
    questionText: "What is the primary function of the Crew Escape System (CES) on ISRO's Human Rated LVM3 (HLVM3) rocket?",
    options: [
      { label: "A", text: "To guide the crew module into its designated Low Earth Orbit." },
      { label: "B", text: "To eject the crew module to safety during launch emergencies." },
      { label: "C", text: "To assist in docking the crew module with a space station." },
      { label: "D", text: "To provide thermal shielding during re-entry into Earth's atmosphere." },
    ],
    correctOption: "B",
  },
  {
    questionNo: 36,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following statements about Justice Sanjiv Khanna is/are true?\n1. He is the 51st Chief Justice of India\n2. He succeeded Justice D.Y. Chandrachud\n3. He served as CJI from 2023",
    options: [
      { label: "A", text: "1 and 2 only" },
      { label: "B", text: "2 and 3 only" },
      { label: "C", text: "1 and 3 only" },
      { label: "D", text: "1, 2, and 3 all are true" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 37,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following objectives are part of the National Population Policy (NPP) 2000?\n1. Providing free and compulsory education up to 14 years of age\n2. Increasing fertility rate to ensure demographic dividend\n3. Reducing infant mortality rate below 30 per 1000 live births\n4. Promoting delayed marriage for girls",
    options: [
      { label: "A", text: "Only 1 and 2 are correct" },
      { label: "B", text: "Only 1 and 3 are correct" },
      { label: "C", text: "Only 1, 3 and 4 are correct" },
      { label: "D", text: "1, 2, 3 and 4 all are correct" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 38,
    part: "B",
    partName: "General Awareness",
    questionText: "Which pathway in cellular respiration generates the most ATP?",
    options: [
      { label: "A", text: "Glycolysis" },
      { label: "B", text: "Krebs cycle" },
      { label: "C", text: "Electron transport chain" },
      { label: "D", text: "Fermentation" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 39,
    part: "B",
    partName: "General Awareness",
    questionText: "Arrange the following events in chronological order:\na. Eastern Zonal Council meeting 2022\nb. States Reorganisation Act passed\nc. First Central Zonal Council meeting",
    options: [
      { label: "A", text: "b-c-a" },
      { label: "B", text: "c-b-a" },
      { label: "C", text: "a-b-c" },
      { label: "D", text: "b-a-c" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 40,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following most accurately describes the legal character of the right to property under Article 300A of the Indian Constitution?",
    options: [
      { label: "A", text: "It is a fundamental right that guarantees compensation for all property acquisitions." },
      { label: "B", text: "It allows the State to deprive a person of property by any law, even without due process." },
      { label: "C", text: "It is a constitutional legal right that permits deprivation only by authority of law." },
      { label: "D", text: "It permits citizens to claim property protection under Article 32 before the Supreme Court." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 41,
    part: "B",
    partName: "General Awareness",
    questionText: "For a rigid body, the angular velocity of any particle about a given axis of rotation is:",
    options: [
      { label: "A", text: "Proportional to its distance from the axis" },
      { label: "B", text: "The same for all particles" },
      { label: "C", text: "Inversely proportional to its distance from the axis" },
      { label: "D", text: "Always zero" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 42,
    part: "B",
    partName: "General Awareness",
    questionText: "The Bharatiya Sakshya Adhiniyam (BSA) places emphasis on the use of technology to ensure the authenticity of evidence. This is particularly relevant for:",
    options: [
      { label: "A", text: "Physical exhibits from crime scenes." },
      { label: "B", text: "Hand-written diaries." },
      { label: "C", text: "Digital and electronic evidence." },
      { label: "D", text: "Oral confessions." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 43,
    part: "B",
    partName: "General Awareness",
    questionText: "Assertion (A): The One Nation One Ration Card ensures portability of food grains.\nReason (R): It uses Aadhaar-enabled biometric authentication.",
    options: [
      { label: "A", text: "Both A and R are true, and R is the correct explanation of A" },
      { label: "B", text: "Both A and R are true, but R is not the correct explanation of A" },
      { label: "C", text: "A is true, but R is false" },
      { label: "D", text: "A is false, but R is true" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 44,
    part: "B",
    partName: "General Awareness",
    questionText: "Cheraw, the bamboo dance performed using crossed bamboo sticks, is a folk dance of which state?",
    options: [
      { label: "A", text: "Mizoram" },
      { label: "B", text: "Meghalaya" },
      { label: "C", text: "Arunachal Pradesh" },
      { label: "D", text: "Sikkim" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 45,
    part: "B",
    partName: "General Awareness",
    questionText: "What is a key factor assessed in the Global Firepower Military Strength Ranking 2025?",
    options: [
      { label: "A", text: "Economic Stability" },
      { label: "B", text: "Cultural Influence" },
      { label: "C", text: "Defense Budget" },
      { label: "D", text: "Healthcare Spending" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 46,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following correctly describes cooperative sector industries?",
    options: [
      { label: "A", text: "Owned and operated by central government agencies." },
      { label: "B", text: "Operated solely for export purposes." },
      { label: "C", text: "Owned by workers or suppliers sharing profits and losses." },
      { label: "D", text: "Maintained by foreign companies with Indian partnerships." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 47,
    part: "B",
    partName: "General Awareness",
    questionText: "Education is now placed under which list after the 42nd Amendment?",
    options: [
      { label: "A", text: "Union List" },
      { label: "B", text: "State List" },
      { label: "C", text: "Concurrent List" },
      { label: "D", text: "Judicial List" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 48,
    part: "B",
    partName: "General Awareness",
    questionText: "What is the main objective of the National Framework for Climate Services (NFCS) launched in 2024?",
    options: [
      { label: "A", text: "To set emission trading targets" },
      { label: "B", text: "To regulate groundwater quality" },
      { label: "C", text: "To deliver sector-specific climate information services" },
      { label: "D", text: "To mandate carbon offsetting in the private sector" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 49,
    part: "B",
    partName: "General Awareness",
    questionText: "Argon is produced in Earth's crust via?",
    options: [
      { label: "A", text: "Decay of K-40" },
      { label: "B", text: "Volcanoes" },
      { label: "C", text: "Photosynthesis" },
      { label: "D", text: "Cosmic rays" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 50,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following is true about Fundamental Rights and DPSPs?",
    options: [
      { label: "A", text: "Both are justiciable and enforceable by courts" },
      { label: "B", text: "DPSPs override Fundamental Rights when in conflict" },
      { label: "C", text: "Fundamental Rights are justiciable, but DPSPs are not" },
      { label: "D", text: "DPSPs are guaranteed by the Constitution; Fundamental Rights are optional" },
    ],
    correctOption: "C",
  },

  // ===== PART C: Quantitative Aptitude (Q.51-Q.75) =====
  {
    questionNo: 51,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Arrange the fractions 5/9, 4/7, 3/5, and 2/3 in ascending order.",
    options: [
      { label: "A", text: "3/5, 4/7, 2/3, 5/9" },
      { label: "B", text: "5/9, 4/7, 3/5, 2/3" },
      { label: "C", text: "2/3, 3/5, 4/7, 5/9" },
      { label: "D", text: "4/7, 5/9, 2/3, 3/5" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 52,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: (2½ + 3.6) − 1.9",
    options: [
      { label: "A", text: "4.2" },
      { label: "B", text: "5.2" },
      { label: "C", text: "6.2" },
      { label: "D", text: "7.2" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 53,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Evaluate: 7¼ − [5/6 ÷ {1/3 − (1/2 × (3/4 − 1/4))}]",
    options: [
      { label: "A", text: "−3¼" },
      { label: "B", text: "3¼" },
      { label: "C", text: "−2¾" },
      { label: "D", text: "2¾" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 54,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "From a sample of 200 software engineers, determine the ratio of those proficient in Python to those proficient in Java using the given information:\nProficient in Python and Java: 50\nProficient in Python only: 70\nProficient in Java only: 60\nProficient in neither: 20",
    options: [
      { label: "A", text: "11:12" },
      { label: "B", text: "12:11" },
      { label: "C", text: "7:6" },
      { label: "D", text: "6:7" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 55,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Arvind started a business by investing ₹80,000. After 4 months, Bhavin joined with ₹1,20,000. At the end of 8 months from the start, Chandan joined with ₹1,60,000. If the total profit is ₹1,05,000 at the end of the year, find the share of Chandan.",
    options: [
      { label: "A", text: "₹26,500" },
      { label: "B", text: "₹26,000" },
      { label: "C", text: "₹26,200" },
      { label: "D", text: "₹26,250" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 56,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A and B start a business. A invests ₹80,000 for 9 months, B invests ₹1,20,000 for 6 months. What is B's share of a ₹45,000 profit?",
    options: [
      { label: "A", text: "₹26,500" },
      { label: "B", text: "₹28,000" },
      { label: "C", text: "₹36,000" },
      { label: "D", text: "₹22,500" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 57,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "What is the average of all integers between 100 and 250 that are exactly divisible by 11?",
    options: [
      { label: "A", text: "176" },
      { label: "B", text: "186" },
      { label: "C", text: "196" },
      { label: "D", text: "146" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 58,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The average of 15 numbers is 80. The average of the first 6 numbers is 72. The average of the next 6 numbers is 25% more than the average of the first 6 numbers. The 13th number is 8 more than the 15th number, and the 14th number is 10 less than the 15th number. What is the average of the 13th and 14th numbers?",
    options: [
      { label: "A", text: "70.89" },
      { label: "B", text: "85" },
      { label: "C", text: "75.67" },
      { label: "D", text: "80.65" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 59,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A landlord bought a flat for ₹8,00,000. He wants to earn a 9% annual return on his investment after paying ₹2,000 per month for maintenance. What should be the monthly rent he charges?",
    options: [
      { label: "A", text: "₹7,000" },
      { label: "B", text: "₹7,500" },
      { label: "C", text: "₹8,000" },
      { label: "D", text: "₹8,500" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 60,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "An amount is said to double in 5 years with compound interest. How many years will it take for the amount to grow to 8 times its original value?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "16" },
      { label: "C", text: "17" },
      { label: "D", text: "18" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 61,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A sum becomes ₹6,600 in 2 years and ₹7,920 in 3 years at compound interest. What is the original principal?",
    options: [
      { label: "A", text: "₹4,000.33" },
      { label: "B", text: "₹5,583.33" },
      { label: "C", text: "₹4,583.33" },
      { label: "D", text: "₹6,583.33" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 62,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Suman purchased 25 liters of milk at ₹45 per liter and another 15 liters of milk at ₹50 per liter. She combined both quantities and then sold the entire mixture at ₹48 per liter. What was her total profit or loss?",
    options: [
      { label: "A", text: "Loss of ₹45" },
      { label: "B", text: "Profit of ₹45" },
      { label: "C", text: "Profit of ₹90" },
      { label: "D", text: "Loss of ₹90" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 63,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A toy manufacturer produced 1200 toy cars at a total cost of ₹90,000. He donated 200 cars to a charity event. For the rest, he announced a 10% discount on the market price of ₹120 per car. He also offered 2 toy cars free for every 8 toy cars purchased. If all 1200 toy cars were distributed, what is his overall gain or loss percentage?",
    options: [
      { label: "A", text: "4% loss" },
      { label: "B", text: "4% profit" },
      { label: "C", text: "5% loss" },
      { label: "D", text: "5% profit" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 64,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A retailer marks an air conditioner 80% above its cost price. He offers a first discount of 25% on the marked price. During a festive offer, an additional discount of 10% is applied on the already discounted price. If the final selling price is ₹15,552, what is the approximate cost price of the air conditioner?",
    options: [
      { label: "A", text: "₹9,000" },
      { label: "B", text: "₹9,200" },
      { label: "C", text: "₹12,800" },
      { label: "D", text: "₹10,000" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 65,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A 40-liter mixture contains juice and water in the ratio 5:3. How much water (in liters) must be added to this mixture to change the ratio of juice to water to 2:3?",
    options: [
      { label: "A", text: "15.5 litres" },
      { label: "B", text: "22.5 litres" },
      { label: "C", text: "25 litres" },
      { label: "D", text: "30 litres" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 66,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A is able to complete a task in 15 days, while B takes 20 days to finish the same task. If they collaborate and work together for 4 days, what fraction of the work will still remain?",
    options: [
      { label: "A", text: "1/4" },
      { label: "B", text: "7/15" },
      { label: "C", text: "8/15" },
      { label: "D", text: "11/15" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 67,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two oils priced at ₹90 per kg and ₹150 per kg are blended and sold at ₹144 per kg, achieving a profit margin of 20%. What is the ratio of the two oils in the mixture?",
    options: [
      { label: "A", text: "1 : 1" },
      { label: "B", text: "2 : 1" },
      { label: "C", text: "3 : 2" },
      { label: "D", text: "4 : 1" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 68,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Three pipes, A, B, and C are capable of filling a tank in 6, 8, and 12 hours, respectively. When all three pipes are opened together, they operate for 2 hours before pipe C is closed. How much additional time will it take to completely fill the tank after that?",
    options: [
      { label: "A", text: "6/7 hours" },
      { label: "B", text: "2/6 hours" },
      { label: "C", text: "3/5 hours" },
      { label: "D", text: "9/2 hours" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 69,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A bullet train covers a fixed distance in 30 minutes at an average speed of 240 km/h. Due to track maintenance, it needs to be diverted, increasing the distance by 20%. If the train needs to arrive at its destination on time (i.e., in 30 minutes), what should its new average speed be in km/h?",
    options: [
      { label: "A", text: "280 km/h" },
      { label: "B", text: "300 km/h" },
      { label: "C", text: "288 km/h" },
      { label: "D", text: "320 km/h" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 70,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two cars, X and Y, start from points 360 km apart and travel at constant speeds. If they move towards each other, they meet in 4 hours. If they move in the same direction, they meet in 12 hours. What is the speed of car X? (Assume X is the faster car).",
    options: [
      { label: "A", text: "60 km/h" },
      { label: "B", text: "75 km/h" },
      { label: "C", text: "45 km/h" },
      { label: "D", text: "90 km/h" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 71,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A circular pizza having a radius of 21 cm. If 75% of it is eaten, what is the area of pizza remaining?",
    options: [
      { label: "A", text: "173.25 cm²" },
      { label: "B", text: "346.36 cm²" },
      { label: "C", text: "432.25 cm²" },
      { label: "D", text: "115.5 cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 72,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A ring-shaped disc has outer radius 10 cm and inner radius 7 cm. What is the approximate ratio of the ring's area to the whole outer circle?",
    options: [
      { label: "A", text: "1:2" },
      { label: "B", text: "2:3" },
      { label: "C", text: "3:4" },
      { label: "D", text: "4:5" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 73,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A bicycle wheel having a radius of 35 cm. What percentage of its circumference is covered in a quarter turn? (Use π = 22/7)",
    options: [
      { label: "A", text: "15%" },
      { label: "B", text: "25%" },
      { label: "C", text: "30%" },
      { label: "D", text: "35%" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 74,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The line y = mx + 5 passes through (1, 8). Find m.",
    options: [
      { label: "A", text: "5" },
      { label: "B", text: "4" },
      { label: "C", text: "3" },
      { label: "D", text: "2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 75,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "31³ + 18³ − 37³ + 210 is equal to:",
    options: [
      { label: "A", text: "−36810" },
      { label: "B", text: "−14820" },
      { label: "C", text: "−45670" },
      { label: "D", text: "−23450" },
    ],
    correctOption: "B",
  },

  // ===== PART D: English Comprehension (Q.76-Q.100) =====
  {
    questionNo: 76,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate synonym of the given word: PERFIDIOUS",
    options: [
      { label: "A", text: "Honest" },
      { label: "B", text: "Faithful" },
      { label: "C", text: "Treacherous" },
      { label: "D", text: "Loyal" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 77,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct meaning of idiom: Hobson's choice",
    options: [
      { label: "A", text: "A dilemma between two evils" },
      { label: "B", text: "A free and fair decision" },
      { label: "C", text: "No real choice at all" },
      { label: "D", text: "A selection made under duress" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 78,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: Perfidious",
    options: [
      { label: "A", text: "Betraying" },
      { label: "B", text: "Faithless" },
      { label: "C", text: "Loyal" },
      { label: "D", text: "Treacherous" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 79,
    part: "D",
    partName: "English Comprehension",
    questionText: "Identify the misspelt word",
    options: [
      { label: "A", text: "Vicereine" },
      { label: "B", text: "Floccinaucinihilipilification" },
      { label: "C", text: "Defenestrate" },
      { label: "D", text: "Quintessance" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 80,
    part: "D",
    partName: "English Comprehension",
    questionText: "Spot the correct spelling of a CSF-shunt procedure.",
    options: [
      { label: "A", text: "Ventriculoperitoneal" },
      { label: "B", text: "Ventriculoperitonal" },
      { label: "C", text: "Ventriculaperitoneal" },
      { label: "D", text: "Ventriculoperetoneal" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 81,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitute for: 'An official reprimand or strong criticism'.",
    options: [
      { label: "A", text: "Accusation" },
      { label: "B", text: "Denunciation" },
      { label: "C", text: "Censure" },
      { label: "D", text: "Indictment" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 82,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the correct option:\nThe startup scaled so rapidly that its infrastructure could ___ keep pace.",
    options: [
      { label: "A", text: "barely" },
      { label: "B", text: "merely" },
      { label: "C", text: "scarcely" },
      { label: "D", text: "all but" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 83,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the correct option:\nRare though the phenomenon is, it can occur ___ prolonged drought conditions.",
    options: [
      { label: "A", text: "towards" },
      { label: "B", text: "amid" },
      { label: "C", text: "among" },
      { label: "D", text: "under" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 84,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the correct option:\nWhile the proposal appeared pragmatic on paper, its implementation proved ___ complicated than expected.",
    options: [
      { label: "A", text: "less" },
      { label: "B", text: "more" },
      { label: "C", text: "much" },
      { label: "D", text: "rather" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 85,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nThat the report failed to address the root causes (1)/ of the community unrest were surprising (2)/ given the exhaustive data (3)/ compiled over several months. (4)",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 86,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nWhat renders the draft legislation particularly contentious is not its proposed realignment of fiscal powers per se, (1)/ but that it presumes, without empirical substantiation, (2)/ a fiscal equivalence among states whose developmental baselines are (3)/ incommensurable by any normative metric. (4)",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 87,
    part: "D",
    partName: "English Comprehension",
    questionText: "Change the following from active to passive:\nThey have been neglecting maintenance of the archives for years.",
    options: [
      { label: "A", text: "Maintenance of the archives had been neglected by them for years." },
      { label: "B", text: "Maintenance of the archives is being neglected by them for years." },
      { label: "C", text: "Maintenance of the archives was being neglected by them for years." },
      { label: "D", text: "Maintenance of the archives has been being neglected by them for years." },
    ],
    correctOption: "D",
  },
  {
    questionNo: 88,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the sentence containing the homonym of the highlighted word:\nThe choir began the introit at the priest's signal.",
    options: [
      { label: "A", text: "The child sang the introit during the intermission." },
      { label: "B", text: "The introit was replaced by an organ improvisation." },
      { label: "C", text: "The missal included Latin text for the introit." },
      { label: "D", text: "The cantor rehearsed the Sunday introit." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 89,
    part: "D",
    partName: "English Comprehension",
    questionText: "Convert the sentence provided below from its passive voice structure to an active voice structure:\nIt was being suggested by multiple sources that the operation had been compromised internally.",
    options: [
      { label: "A", text: "Multiple sources suggested the operation was compromised internally." },
      { label: "B", text: "The operation was compromised, multiple sources suggested." },
      { label: "C", text: "The sources were suggesting an operation compromise." },
      { label: "D", text: "The operation had compromised multiple internal sources." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 90,
    part: "D",
    partName: "English Comprehension",
    questionText: "According to the passage, how is wisdom primarily acquired?",
    options: [
      { label: "A", text: "Through textbooks" },
      { label: "B", text: "Through emotional detachment" },
      { label: "C", text: "Through experience and reflection" },
      { label: "D", text: "Through algorithmic thinking" },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 91,
    part: "D",
    partName: "English Comprehension",
    questionText: 'What does the author mean by "wisdom enriches the soul"?',
    options: [
      { label: "A", text: "It enhances academic success" },
      { label: "B", text: "It fosters deeper moral insight" },
      { label: "C", text: "It improves verbal expression" },
      { label: "D", text: "It sharpens mathematical skills" },
    ],
    correctOption: "B",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 92,
    part: "D",
    partName: "English Comprehension",
    questionText: "Who, according to the author, can be wise despite lacking formal education?",
    options: [
      { label: "A", text: "Scientists" },
      { label: "B", text: "School children" },
      { label: "C", text: "Elders and artisans" },
      { label: "D", text: "Technocrats" },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 93,
    part: "D",
    partName: "English Comprehension",
    questionText: "What is the central contrast drawn in the passage?",
    options: [
      { label: "A", text: "Education vs. career" },
      { label: "B", text: "Intelligence vs. memory" },
      { label: "C", text: "Reading vs. writing" },
      { label: "D", text: "Formal learning vs. applied wisdom" },
    ],
    correctOption: "D",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 94,
    part: "D",
    partName: "English Comprehension",
    questionText: "According to the author, why has the gap between education and wisdom widened in recent times?",
    options: [
      { label: "A", text: "Due to overuse of social media" },
      { label: "B", text: "Because wisdom is no longer valued" },
      { label: "C", text: "Because of rote learning and algorithmic methods" },
      { label: "D", text: "Because people stop learning after school" },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 95,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nShe has the reputation to be a kind woman.",
    options: [
      { label: "A", text: "to have kindness" },
      { label: "B", text: "of being a kind woman" },
      { label: "C", text: "of being the kind woman" },
      { label: "D", text: "to be kind-hearted" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 96,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nThe doctor advised him to avoid eating sweets and doing exercise regularly.",
    options: [
      { label: "A", text: "avoiding sweets and doing regular exercise" },
      { label: "B", text: "to avoid sweets and to exercises regularly" },
      { label: "C", text: "to avoid eating sweets and to exercise regularly" },
      { label: "D", text: "to not eat sweets and do exercises" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 97,
    part: "D",
    partName: "English Comprehension",
    questionText: 'A sentence is provided in direct speech. Choose the one that most accurately conveys it in indirect speech.\nHe asked me, "Have you done your homework?"',
    options: [
      { label: "A", text: "He asked me if I had done my homework." },
      { label: "B", text: "He asked me have I done my homework." },
      { label: "C", text: "He asked me whether I have done my homework." },
      { label: "D", text: "He asked me whether had I done my homework." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 98,
    part: "D",
    partName: "English Comprehension",
    questionText: "A sentence is provided in indirect speech. Choose the one that most accurately conveys it in direct speech.\nHe said that he would join the meeting after lunch.",
    options: [
      { label: "A", text: '"I will join the meeting after lunch," he said.' },
      { label: "B", text: '"I would join the meeting after lunch," he said.' },
      { label: "C", text: '"I shall join the meeting after lunch," he said.' },
      { label: "D", text: '"I can join the meeting after lunch," he said.' },
    ],
    correctOption: "A",
  },
  {
    questionNo: 99,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences in correct order to make a logical passage:\n1. A media strategy was framed based on outreach results.\n2. Demographic metrics were tracked from campaign dashboards.\n3. User interactions were collected across platforms.\n4. Analysts segmented users by age and behavior.",
    options: [
      { label: "A", text: "3-2-4-1" },
      { label: "B", text: "2-3-1-4" },
      { label: "C", text: "3-1-4-2" },
      { label: "D", text: "4-1-2-3" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 100,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. It is a process that involves the systematic and objective investigation of a subject to discover new facts or to confirm existing ones.\n2. Research is a foundational pillar of academic and scientific progress.\n3. This can be either theoretical, aiming to expand knowledge, or applied, seeking to solve a practical problem.\n4. The findings of this investigation are then documented and peer-reviewed to ensure validity and credibility.",
    options: [
      { label: "A", text: "2, 1, 3, 4" },
      { label: "B", text: "1, 2, 4, 3" },
      { label: "C", text: "4, 3, 2, 1" },
      { label: "D", text: "3, 4, 1, 2" },
    ],
    correctOption: "A",
  },
];
