export interface QuestionData {
  questionNo: number;
  part: string;
  partName: string;
  questionText: string;
  options: { label: string; text: string }[];
  correctOption: string;
  passage?: string;
}

export interface PaperInfo {
  id: string;
  title: string;
  date: string;
  shift: string;
  questions: QuestionData[];
}

const PASSAGE_90_94 = `In the labyrinth of globalization, where intercontinental dialogues shape diplomacy, business, and social cohesion, the intricate terrain of cross-cultural communication remains one of the most formidable cognitive frontiers. Misunderstandings often arise not from lexical deficiencies but from semiotic dissonance—where gestures, silences, intonations, or proxemics are interpreted through incongruent cultural lenses. The assumption that language fluency equates to communicative efficacy is a pernicious fallacy; in reality, fluency may obfuscate cultural asymmetries, allowing misinterpretation to masquerade as comprehension. In high-context cultures—such as Japan or the Arab world—communication is embedded in relational nuance, tacit implications, and communal hierarchies. Conversely, low-context cultures like Germany or the United States prioritize explicitness, objectivity, and individual clarity. When interlocutors from these paradigms converge, the mismatch can generate diplomatic friction, transactional inefficiency, or interpersonal alienation. Even seemingly innocuous behaviors—eye contact, turn-taking, or humor—can catalyze discomfort when interpreted through a monocultural lens. Furthermore, the cognitive filters individuals deploy—shaped by education, tradition, and sociopolitical conditioning—often reinforce in-group validation while relegating unfamiliar communication styles to categories of deviance or incompetence. This ethnocentric predisposition exacerbates stereotyping, reduces empathetic bandwidth, and curtails the potential for collaborative synergy. Technology, while ostensibly bridging geographic divides, further complicates intercultural interaction. Emojis, for instance, are semantically fluid; a single icon may evoke warmth in one culture and sarcasm in another. Algorithmic translation, lacking context-sensitivity, risks converting diplomatic nuance into semantic absurdity. Even video conferencing flattens paralinguistic cues vital to cross-cultural understanding. Ultimately, transcending these communicative chasms demands metacognitive vigilance, cultural humility, and dialogic adaptability. Effective intercultural communicators do not merely learn linguistic syntax but cultivate cultural empathy, interrogate their own perceptual frameworks, and develop a tolerance for ambiguity. It is within this cognitive dissonance that the richest intercultural growth unfolds—not through the elimination of difference, but through its embrace.`;

const paper16Sep: QuestionData[] = [
  // ===== PART A: General Intelligence and Reasoning (Q.1-Q.25) =====
  {
    questionNo: 1,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Sentence: "Reflections are clearer in calm waters." If each letter is mirrored using alphabetical symmetry (A↔Z, B↔Y...), what is the 2nd letter of the 6th word after mirroring?',
    options: [
      { label: "A", text: "d" },
      { label: "B", text: "x" },
      { label: "C", text: "y" },
      { label: "D", text: "z" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 2,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Choose the address that is exactly the same as the one given below.\nFlat 201, Sapphire Tower, Garia Station Rd., Kolkata, West Bengal – 700084",
    options: [
      { label: "A", text: "Flat 201, Saphire Tower, Garia Station Rd., Kolkata, West Bengal – 700084" },
      { label: "B", text: "Flat 201, Sapphire Tower, Garia Station Rd., Kolkata, West Bengal – 700084" },
      { label: "C", text: "Flat 201, Sapphire Tower, Gariya Station Rd., Kolkata, West Bengal – 700084" },
      { label: "D", text: "Flat 201, Sapphire Tower, Garia Station Road, Kolkata, West Bengal – 700084" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 3,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following alternative will fill the blanks?\nm_u_mg_p_gu_",
    options: [
      { label: "A", text: "g,p,u,m,p" },
      { label: "B", text: "g,p,u,p,m" },
      { label: "C", text: "p,u,u,p,m" },
      { label: "D", text: "p,p,u,m,g" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 4,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series:\nGBDF, GHMR, GNVD, GTEP, ?",
    options: [
      { label: "A", text: "G Z M B" },
      { label: "B", text: "G Z N C" },
      { label: "C", text: "G Z N B" },
      { label: "D", text: "G Y N B" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 5,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 'Z' denotes 'addition', 'X' denotes 'multiplication', 'Y' denotes 'division', and 'W' denotes 'subtraction', then what will be the value of the following expression?\n3.2 Z (0.56 Y 1.4 X 4) W 5 X 5 Y 25 Z 5.",
    options: [
      { label: "A", text: "6.9" },
      { label: "B", text: "8.8" },
      { label: "C", text: "8.6" },
      { label: "D", text: "9.8" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 6,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out:\nA@1A, B@2B, C@4C, D@4D",
    options: [
      { label: "A", text: "A@1A, B@2B" },
      { label: "B", text: "B@2B, C@4C" },
      { label: "C", text: "C@4C, D@4D" },
      { label: "D", text: "A@1A, D@4D" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 7,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What will come at the place of question mark?\n1, 3, 7, 15, 31, ?",
    options: [
      { label: "A", text: "62" },
      { label: "B", text: "63" },
      { label: "C", text: "64" },
      { label: "D", text: "65" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 8,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Instruction: Identify the assumptions that must hold for the statement to be valid, then choose the correct option.\nStatement: Deforestation in tropical rainforests, primarily driven by agricultural expansion and logging, not only contributes to the loss of biodiversity but also exacerbates global warming by reducing the Earth's capacity to absorb carbon dioxide.\nAssumptions:\nI. Deforestation reduces the Earth's ability to absorb carbon dioxide.\nII. Agricultural expansion and logging are the primary causes of deforestation.\nIII. The loss of biodiversity is the most significant consequence of deforestation.",
    options: [
      { label: "A", text: "Only I and II are implicit" },
      { label: "B", text: "Only II and III are implicit" },
      { label: "C", text: "Only I is implicit" },
      { label: "D", text: "All I, II and III are implicit" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 9,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Read the following statement carefully and identify the conclusion that follows.\nStatement: The city experienced its worst rainfall in 50 years.\nConclusions:\nI. The city's drainage systems may have failed.\nII. Such rainfall occurs regularly.",
    options: [
      { label: "A", text: "Only Conclusion I follows" },
      { label: "B", text: "Only Conclusion II follows" },
      { label: "C", text: "Both I and II follow" },
      { label: "D", text: "Neither I nor II follows" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 10,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'How many meaningful four-letter English words can be formed using the first, second, third, and fifth letters of the word "TRAVEL" (when counted from left to right), using each letter only once in each word?',
    options: [
      { label: "A", text: "One" },
      { label: "B", text: "Three" },
      { label: "C", text: "Two" },
      { label: "D", text: "Five" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 11,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In the following question, a pair of letters is given, followed by its corresponding product of alphabetical positions (A = 1, B = 2, ..., Z = 26). A second pair is given without its product. Identify the correct product for the second pair that maintains the same relationship as the first.\nNxP : 14×16 :: ExI : ?",
    options: [
      { label: "A", text: "5×9" },
      { label: "B", text: "6×9" },
      { label: "C", text: "5×10" },
      { label: "D", text: "6×8" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 12,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Complete the series.\nZ1, Y2, X3, W4, ?",
    options: [
      { label: "A", text: "V5" },
      { label: "B", text: "V4" },
      { label: "C", text: "U5" },
      { label: "D", text: "X5" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 13,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out from the given alternatives:\nArticle 14, Article 19, Article 21, Article 370",
    options: [
      { label: "A", text: "Article 14" },
      { label: "B", text: "Article 19" },
      { label: "C", text: "Article 21" },
      { label: "D", text: "Article 370" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 14,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "A is the daughter of B. B is the son of C. D is the wife of C. How is D related to A?",
    options: [
      { label: "A", text: "Aunt" },
      { label: "B", text: "Mother" },
      { label: "C", text: "Grandmother" },
      { label: "D", text: "Sister" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 15,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 3 + 4 = 19 and 2 + 5 = 17, what is 1 + 6 = ?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "13" },
      { label: "C", text: "12" },
      { label: "D", text: "11" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 16,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In a certain code language, each letter is assigned a unique digit. Based on the given codes for specific words, determine the code for the target word using the same logic.\nIf SPEED is coded as 83551 and COOL is coded as 9226, then how will SCOOP be coded?",
    options: [
      { label: "A", text: "89213" },
      { label: "B", text: "89276" },
      { label: "C", text: "89223" },
      { label: "D", text: "89327" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 17,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 5 * 4 = 41 and 6 * 3 = 45, what is 7 * 2?",
    options: [
      { label: "A", text: "48" },
      { label: "B", text: "51" },
      { label: "C", text: "53" },
      { label: "D", text: "55" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 18,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 'READ' is coded as T2@3, and 'DEAR' is coded as 3@2T, then what is the code for 'DARE'?",
    options: [
      { label: "A", text: "3@T2" },
      { label: "B", text: "T@23" },
      { label: "C", text: "@32T" },
      { label: "D", text: "@32Y" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 19,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What is the average of 5 consecutive odd numbers starting from 13?",
    options: [
      { label: "A", text: "17" },
      { label: "B", text: "18" },
      { label: "C", text: "20" },
      { label: "D", text: "23" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 20,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If the given symbols mean:\n'+' means 'divided by'\n'−' means 'multiplied by'\n'×' means 'minus'\n'÷' means 'plus'\nThen, find the value of the following expression:\n36 + 12 − 3 × 8 ÷ 5 = ?",
    options: [
      { label: "A", text: "6" },
      { label: "B", text: "27" },
      { label: "C", text: "48" },
      { label: "D", text: "36" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 21,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Pointing to a photograph, a man says, "She is the daughter of the only son of my father\'s wife". Who is the woman to the man?',
    options: [
      { label: "A", text: "Sister" },
      { label: "B", text: "Cousin" },
      { label: "C", text: "Niece" },
      { label: "D", text: "Daughter" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 22,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If '×' = '+', '÷' = '−', '−' = '÷', '+' = '×', which equation is correct?",
    options: [
      { label: "A", text: "10 + 2 × 2 − 4 = 10" },
      { label: "B", text: "14 ÷ 2 − 2 + 4 = 10" },
      { label: "C", text: "12 × 2 + 4 − 1 = 27" },
      { label: "D", text: "8 + 4 − 2 × 1 = 10" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 23,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Read the following statements and evaluate the conclusions based on traditional syllogistic logic. Consider the statements to be absolutely true, even if they appear contrary to known facts. Determine which conclusion(s) logically follow from the given statements.\nStatements:\nAll metals are elements.\nSome elements are gases.\nConclusions:\nI. Some metals are gases.\nII. All gases being elements is a possibility.",
    options: [
      { label: "A", text: "Only Conclusion II follows" },
      { label: "B", text: "Both I and II follow" },
      { label: "C", text: "Only Conclusion I follows" },
      { label: "D", text: "Neither I nor II follows" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 24,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If '+' means '×', '−' means '÷', 'x' means '+', then 4 − 2 × 3 + 6 = ?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "6" },
      { label: "C", text: "5" },
      { label: "D", text: "20" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 25,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "The ratio of two numbers is 4:5 and their sum is 180. Find the numbers.",
    options: [
      { label: "A", text: "60 and 75" },
      { label: "B", text: "72 and 108" },
      { label: "C", text: "80 and 100" },
      { label: "D", text: "64 and 116" },
    ],
    correctOption: "C",
  },

  // ===== PART B: General Awareness (Q.26-Q.50) =====
  {
    questionNo: 26,
    part: "B",
    partName: "General Awareness",
    questionText: "What feature was used on Golconda Fort's gates to protect it during attacks involving war elephants?",
    options: [
      { label: "A", text: "Deep moat with water channels" },
      { label: "B", text: "Electrified spikes" },
      { label: "C", text: "Steel spikes on doors" },
      { label: "D", text: "Stone cannon towers" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 27,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following best captures the core rituals and symbolism of the Fagli (Kus/Kuns) festival in Pattan Valley?",
    options: [
      { label: "A", text: "Baraza, symbolizing Shikhara-Appa, is made with marigold and turmeric and placed at village shrines." },
      { label: "B", text: "Punha involves symbolic ploughing indoors using willow sticks, reflecting farming hopes during snow." },
      { label: "C", text: "Totu, made of wheat and honey, is offered on rooftops to priests, then fed to goats." },
      { label: "D", text: "Kwari sweets are made by elder women for temple offerings, as men chant to crow spirits." },
    ],
    correctOption: "B",
  },
  {
    questionNo: 28,
    part: "B",
    partName: "General Awareness",
    questionText: "Determine the correctly matched Gupta fiscal term with its meaning.",
    options: [
      { label: "A", text: "Hiranya – compulsory labour service" },
      { label: "B", text: "Dhanya – gold tax" },
      { label: "C", text: "Bhoga – king's share of produce" },
      { label: "D", text: "Vaishthika – forced or corvée labour" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 29,
    part: "B",
    partName: "General Awareness",
    questionText: "Which musical instrument from Sikkim is believed to have been the first created for the deity Tetlara Lahadongna, and is associated with mythological origins?",
    options: [
      { label: "A", text: "Niyara Hongsing Ke" },
      { label: "B", text: "Simikla Koom (Binayo)" },
      { label: "C", text: "Yema Dhol" },
      { label: "D", text: "Nagara of Yeba" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 30,
    part: "B",
    partName: "General Awareness",
    questionText: "Karnam Malleswari became the first Indian woman to win an Olympic medal in which sporting discipline?",
    options: [
      { label: "A", text: "Boxing" },
      { label: "B", text: "Athletics" },
      { label: "C", text: "Weightlifting" },
      { label: "D", text: "Long Jump" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 31,
    part: "B",
    partName: "General Awareness",
    questionText: "Match each ruler listed in Column A with their respective period of reign given in Column B:\nA. Qutbuddin Aybak – 1. 1175-1192\nB. Prithviraj Chauhan – 2. 1206-1210\nC. Alauddin Khalji – 3. 1296-1316\nD. Muhammad Tughluq – 4. 1324-1351",
    options: [
      { label: "A", text: "A→1, B→2, C→3, D→4" },
      { label: "B", text: "A→4, B→1, C→3, D→2" },
      { label: "C", text: "A→3, B→1, C→2, D→4" },
      { label: "D", text: "A→2, B→1, C→3, D→4" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 32,
    part: "B",
    partName: "General Awareness",
    questionText: "Fill in the blanks:\nAt the 1984 Summer Olympics, P. T. Usha narrowly missed a bronze medal by ________ of a second.",
    options: [
      { label: "A", text: "One-hundredth" },
      { label: "B", text: "One-tenth" },
      { label: "C", text: "One-thousandth" },
      { label: "D", text: "One-fiftyth" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 33,
    part: "B",
    partName: "General Awareness",
    questionText: "Fill in the Blank:\nDuring India's BRICS Chairship in 2021, key initiatives included the Digital Health Summit and the _____ for environmental cooperation.",
    options: [
      { label: "A", text: "BRICS Water Security Pact" },
      { label: "B", text: "BRICS Alliance for Green Tourism" },
      { label: "C", text: "BRICS Climate Finance Agreement" },
      { label: "D", text: "BRICS Sustainable Energy Forum" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 34,
    part: "B",
    partName: "General Awareness",
    questionText: "Who wrote 'Indica: A Deep Natural History of the Indian Subcontinent'?",
    options: [
      { label: "A", text: "Sanjeev Sanyal" },
      { label: "B", text: "Pranay Lal" },
      { label: "C", text: "Rohan Murty" },
      { label: "D", text: "Tony Joseph" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 35,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following about the men's hockey event at the 38th National Games 2025 is/are correct?\n1.) Karnataka beat Uttar Pradesh 3-2 in the final.\n2.) Karnataka vs Maharashtra semifinal ended 2-2, decided by shootout.\n3.) Punjab won bronze by defeating Maharashtra 1-0.",
    options: [
      { label: "A", text: "Both 1 and 2 are correct" },
      { label: "B", text: "Both 1 and 3 are correct" },
      { label: "C", text: "Both 2 and 3 are correct" },
      { label: "D", text: "1, 2 and 3 all are correct" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 36,
    part: "B",
    partName: "General Awareness",
    questionText: "What initiative did Dr. Jitendra Singh launch in May 2025 as MoS PMO and MoS Personnel?",
    options: [
      { label: "A", text: "National Grievance Redress Portal" },
      { label: "B", text: "e-Civil List 2025 e-book" },
      { label: "C", text: "Central Police Commemoration Day" },
      { label: "D", text: "Digital Land Records Survey" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 37,
    part: "B",
    partName: "General Awareness",
    questionText: "Uttar Pradesh accounted for approximately what percent of India's total population in 2011?",
    options: [
      { label: "A", text: "10%" },
      { label: "B", text: "12%" },
      { label: "C", text: "16%" },
      { label: "D", text: "18%" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 38,
    part: "B",
    partName: "General Awareness",
    questionText: "What does the designation HLVM3 stand for in the Gaganyaan mission context?",
    options: [
      { label: "A", text: "Heavy LVM3" },
      { label: "B", text: "Hybrid LVM3" },
      { label: "C", text: "Human LVM3" },
      { label: "D", text: "High LVM3" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 39,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following minerals is found in large quantities in India and holds high economic importance?",
    options: [
      { label: "A", text: "Copper" },
      { label: "B", text: "Petroleum" },
      { label: "C", text: "Iron ore" },
      { label: "D", text: "Tin" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 40,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the following statements:\n1) Both the Prime Minister (PM) and Chief Minister (CM) can advise dissolution of the respective Lower House.\n2) Only the PM can recommend President's Rule under Article 356 of the Constitution.\nWhich of the statements is/are correct?",
    options: [
      { label: "A", text: "Only 1" },
      { label: "B", text: "Only 2" },
      { label: "C", text: "Both 1 and 2" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 41,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following pairs of type of nutrient – nutrient is correctly matched?",
    options: [
      { label: "A", text: "Micronutrient – Calcium" },
      { label: "B", text: "Macronutrient – Zinc" },
      { label: "C", text: "Micronutrient – Boron" },
      { label: "D", text: "Macronutrient – Iron" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 42,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following pairs is correctly matched regarding electromagnetic devices?",
    options: [
      { label: "A", text: "Electric Generator : Converts electrical energy to mechanical energy." },
      { label: "B", text: "Transformer : Operates on DC current to change voltage." },
      { label: "C", text: "Electromagnet : A permanent magnet." },
      { label: "D", text: "Electric Bell : Uses the magnetic effect of electric current." },
    ],
    correctOption: "D",
  },
  {
    questionNo: 43,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the below statements marked as Assertion (A) and Reason (R). Mark the correct options:\nAssertion (A): Mission Amrit Sarovar promotes water conservation.\nReason (R): It aims to construct 75 ponds in each district by 2024.",
    options: [
      { label: "A", text: "Both A and R are true, and R is the correct explanation of A" },
      { label: "B", text: "Both A and R are true, but R is not the correct explanation of A" },
      { label: "C", text: "A is true, but R is false" },
      { label: "D", text: "A is false, but R is true" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 44,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the statements about Rauf:\n1. It is a women's group dance of Kashmir usually performed at Eid.\n2. Dancers align in two facing rows executing toe-heel footwork called ras.\nWhich is/are correct?",
    options: [
      { label: "A", text: "Only 1 correct" },
      { label: "B", text: "Only 2 correct" },
      { label: "C", text: "Both 1 & 2 correct" },
      { label: "D", text: "Neither 1 nor 2 correct" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 45,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the below statements marked as Assertion (A) and Reason (R). Mark the correct options:\nAssertion (A): India's rank in the Global Happiness Index is lower than most South Asian neighbours.\nReason (R): India's GDP per capita is the lowest in South Asia.",
    options: [
      { label: "A", text: "Both A and R are true, and R is the correct explanation of A." },
      { label: "B", text: "Both A and R are true, but R is not the correct explanation of A." },
      { label: "C", text: "A is true, but R is false." },
      { label: "D", text: "A is false, but R is true." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 46,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Indian river was added to the National River Conservation Plan in 2024?",
    options: [
      { label: "A", text: "Yamuna" },
      { label: "B", text: "Musi" },
      { label: "C", text: "Krishna" },
      { label: "D", text: "Gomti" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 47,
    part: "B",
    partName: "General Awareness",
    questionText: "Article 50 is part of which section of the Constitution?",
    options: [
      { label: "A", text: "Fundamental Duties" },
      { label: "B", text: "Directive Principles of State Policy" },
      { label: "C", text: "Fundamental Rights" },
      { label: "D", text: "Preamble" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 48,
    part: "B",
    partName: "General Awareness",
    questionText: "Arrange the following in chronological order:\n1. GST Council constituted\n2. Constitution (101st Amendment) Act enacted\n3. GST launched\nChoose the correct chronological sequence:",
    options: [
      { label: "A", text: "1-2-3" },
      { label: "B", text: "2-1-3" },
      { label: "C", text: "3-2-1" },
      { label: "D", text: "2-3-1" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 49,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the following Assertion (A) and Reason (R) carefully and choose the correct option.\nAssertion (A): The IPR 1956 created an industrial classification into Schedules A, B, and C.\nReason (R): This was to identify sectors for exclusive state control, joint sectors, and private sector operation.",
    options: [
      { label: "A", text: "Both A and R are true and R is the correct explanation of A." },
      { label: "B", text: "Both A and R are true but R is not the correct explanation of A." },
      { label: "C", text: "A is true but R is false." },
      { label: "D", text: "A is false but R is true." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 50,
    part: "B",
    partName: "General Awareness",
    questionText: "Regarding Earth's major climatic zones:\n1. Tropical zones experience minimal seasonal temperature variation\n2. Temperate zones are characterized by four distinct seasons.\nWhich of the above is/are correct?",
    options: [
      { label: "A", text: "Statement 1 only" },
      { label: "B", text: "Statement 2 only" },
      { label: "C", text: "Both 1 and 2" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },

  // ===== PART C: Quantitative Aptitude (Q.51-Q.75) =====
  {
    questionNo: 51,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If P : Q = 6 : 11, Q : R = 5 : 4, and R : S = 9 : 7, find P : Q : R : S.",
    options: [
      { label: "A", text: "270 : 495 : 396 : 308" },
      { label: "B", text: "6 : 11 : 4 : 7" },
      { label: "C", text: "30 : 55 : 44 : 35" },
      { label: "D", text: "270 : 396 : 495 : 308" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 52,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A bag contains ₹10, ₹5, and ₹2 coins in the ratio 1 : 2 : 3. If the total amount of money in the bag is ₹390, find the number of coins of each kind.",
    options: [
      { label: "A", text: "10 coins of ₹10, 20 of ₹5, and 30 of ₹2" },
      { label: "B", text: "15 coins of ₹10, 30 of ₹5, and 45 of ₹2" },
      { label: "C", text: "20 coins of ₹10, 40 of ₹5, and 60 of ₹2" },
      { label: "D", text: "12 coins of ₹10, 24 of ₹5, and 36 of ₹2" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 53,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A tank holds 5¾ liters of water. If 2.375 liters are drained twice, how much water remains?",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "1¼" },
      { label: "C", text: "1⅜" },
      { label: "D", text: "1½" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 54,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: [(⅔) + (⁴⁄₅ ÷ ⅔)] ÷ [(³⁄₂) − (⅚ × ¾)]",
    options: [
      { label: "A", text: "416/105" },
      { label: "B", text: "418/110" },
      { label: "C", text: "425/250" },
      { label: "D", text: "526/350" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 55,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: (2½ + 3.6) ÷ 0.75 + (1.25 × ⅘)",
    options: [
      { label: "A", text: "137/15" },
      { label: "B", text: "160/15" },
      { label: "C", text: "127/15" },
      { label: "D", text: "148/15" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 56,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A and B invested in a business in the ratio 5:6. The profit ratio was 10:9. If B invested his money for 12 months, for how many months did A invest?",
    options: [
      { label: "A", text: "15 months" },
      { label: "B", text: "16 months" },
      { label: "C", text: "17 months" },
      { label: "D", text: "18 months" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 57,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The average of 9 numbers is 56. When one number is removed, the average becomes 54. What number was removed?",
    options: [
      { label: "A", text: "52" },
      { label: "B", text: "72" },
      { label: "C", text: "82" },
      { label: "D", text: "92" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 58,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Table – Weekly Fuel Usage (litres):\nTruck1: Mon=18, Tue=20, Wed=22, Thu=21, Fri=19\nTruck2: Mon=25, Tue=24, Wed=26, Thu=23, Fri=24\nWhat is the overall average daily fuel usage for both trucks?",
    options: [
      { label: "A", text: "27 litres" },
      { label: "B", text: "22.2 litres" },
      { label: "C", text: "28 litres" },
      { label: "D", text: "21.5 litres" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 59,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A sum becomes ₹12100 in 2 years at 10% Compound Interest annually. Find the principal.",
    options: [
      { label: "A", text: "₹10000" },
      { label: "B", text: "₹11000" },
      { label: "C", text: "₹11500" },
      { label: "D", text: "₹10500" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 60,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A grocer purchased 50 kg of rice at ₹40 per kg and 20 kg of another variety of rice at ₹55 per kg. He mixed the two varieties and sold the entire mixture at ₹48 per kg. Find his total profit or loss in this transaction.",
    options: [
      { label: "A", text: "Loss of ₹260" },
      { label: "B", text: "Loss of ₹240" },
      { label: "C", text: "Profit of ₹260" },
      { label: "D", text: "Loss of ₹290" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 61,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A television set has a marked price of ₹20,000. It is sold after two successive discounts. If the first discount is 15% and the final selling price is ₹15,300, what is the percentage of the second discount?",
    options: [
      { label: "A", text: "10%" },
      { label: "B", text: "12%" },
      { label: "C", text: "14%" },
      { label: "D", text: "15%" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 62,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A manufacturer marked a product 30% above its cost price. He provided a discount to a customer, which resulted in him making a profit of 17%. What was the rate of discount given by the manufacturer?",
    options: [
      { label: "A", text: "24%" },
      { label: "B", text: "50%" },
      { label: "C", text: "60%" },
      { label: "D", text: "10%" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 63,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two containers, A and B, contain mixtures of alcohol and water. Container A has alcohol and water in the ratio 4:1, while Container B has them in the ratio 5:2. If 10 liters are drawn from Container A and 14 liters from Container B, and the contents are mixed in a third container, what is the ratio of alcohol to water in the new mixture?",
    options: [
      { label: "A", text: "3:1" },
      { label: "B", text: "7:2" },
      { label: "C", text: "9:4" },
      { label: "D", text: "11:3" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 64,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If the radius of a sphere is increased to twice its original size, what is the ratio of the new surface area to the original surface area, as well as the proportion of the new volume to the original volume?",
    options: [
      { label: "A", text: "4:1 and 2:1" },
      { label: "B", text: "4:1 and 8:1" },
      { label: "C", text: "8:1 and 4:1" },
      { label: "D", text: "2:1 and 4:1" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 65,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A hemisphere and a cone share the same base and have equal volumes. Given that their common radius is R, determine the height of the cone.",
    options: [
      { label: "A", text: "2R" },
      { label: "B", text: "R" },
      { label: "C", text: "5R" },
      { label: "D", text: "4R" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 66,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A solid hemisphere of radius 10 cm is melted into two cones of equal height. If each cone's radius is 5 cm, what is the height of each cone?",
    options: [
      { label: "A", text: "40 cm" },
      { label: "B", text: "45 cm" },
      { label: "C", text: "50 cm" },
      { label: "D", text: "55 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 67,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If base perimeter = 40 cm, slant height = 10 cm, what is lateral surface area of square pyramid?",
    options: [
      { label: "A", text: "260 cm²" },
      { label: "B", text: "200 cm²" },
      { label: "C", text: "400 cm²" },
      { label: "D", text: "432 cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 68,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two circular pizzas have radii in the ratio 2:3. If the smaller pizza has an area of 100π cm², what is the area of the larger pizza?",
    options: [
      { label: "A", text: "265π cm²" },
      { label: "B", text: "225π cm²" },
      { label: "C", text: "215π cm²" },
      { label: "D", text: "250π cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 69,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "In a triangle ABC, medians AD and BE intersect at G. If the length of median AD is 12 cm, what is the length of the segment AG?",
    options: [
      { label: "A", text: "4 cm" },
      { label: "B", text: "6 cm" },
      { label: "C", text: "8 cm" },
      { label: "D", text: "9 cm" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 70,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two right-angled triangular blocks, ABC and DEF, have ∠B=∠E=90°. If the lengths of the hypotenuses AC and DF are equal, and the sides AB and DE are equal, are the triangles congruent? If so, by what rule?",
    options: [
      { label: "A", text: "Yes, by SSS" },
      { label: "B", text: "Yes, by SAS" },
      { label: "C", text: "Yes, by RHS" },
      { label: "D", text: "Yes, by ASA" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 71,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A right triangle ABC is inscribed in a circle with a diameter of 10 cm. An altitude BD is drawn from the vertex B to the hypotenuse AC. If the length of the leg AB is 6 cm, what is the length of the segment AD?",
    options: [
      { label: "A", text: "3.6 cm" },
      { label: "B", text: "4 cm" },
      { label: "C", text: "4.8 cm" },
      { label: "D", text: "6 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 72,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two circles intersect at two points. Which of the following statements is true?",
    options: [
      { label: "A", text: "The internal tangent is longer than the external tangent" },
      { label: "B", text: "Only two common tangents exist" },
      { label: "C", text: "The number of tangents depends on radii" },
      { label: "D", text: "They must be concentric" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 73,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two circles with radii r₁ and r₂ touch each other externally. If the length of their direct common tangent is T, which of the following is the correct relationship between T, r₁, and r₂?",
    options: [
      { label: "A", text: "T = r₁ + r₂" },
      { label: "B", text: "T = 2(r₁ + r₂)" },
      { label: "C", text: "T = 2√(r₁r₂)" },
      { label: "D", text: "T = r₁² + r₂²" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 74,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A chord of a circle has a length of 12 cm. The angle subtended by the chord at a point on the circumference is 30°. What is the distance from the center of the circle to the chord?",
    options: [
      { label: "A", text: "6√3 cm" },
      { label: "B", text: "3√3 cm" },
      { label: "C", text: "6 cm" },
      { label: "D", text: "3 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 75,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "What is the area of the segment formed by a chord in a circle of radius 8 cm, if the angle subtended at the center is 60°?",
    options: [
      { label: "A", text: "32π/3 − 16√3" },
      { label: "B", text: "64π/3 − 16√3" },
      { label: "C", text: "32π/3 − 8√3" },
      { label: "D", text: "64π/3 − 32√3" },
    ],
    correctOption: "A",
  },

  // ===== PART D: English Comprehension (Q.76-Q.100) =====
  {
    questionNo: 76,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate synonym of the given word: **ILLUMINATE**",
    options: [
      { label: "A", text: "Explain" },
      { label: "B", text: "Darken" },
      { label: "C", text: "Destroy" },
      { label: "D", text: "Hide" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 77,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: **Demur**",
    options: [
      { label: "A", text: "Agree" },
      { label: "B", text: "Oppose" },
      { label: "C", text: "Object" },
      { label: "D", text: "Resist" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 78,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct meaning of the idiom:\n**Eat humble pie**",
    options: [
      { label: "A", text: "To demand an apology" },
      { label: "B", text: "To celebrate one's success" },
      { label: "C", text: "To accept insult or defeat gracefully" },
      { label: "D", text: "To prepare for failure" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 79,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: **Zany**",
    options: [
      { label: "A", text: "Sensible" },
      { label: "B", text: "Bizarre" },
      { label: "C", text: "Clownish" },
      { label: "D", text: "Eccentric" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 80,
    part: "D",
    partName: "English Comprehension",
    questionText: "Spot the correct spelling of weather science.",
    options: [
      { label: "A", text: "Meterology" },
      { label: "B", text: "Meteorology" },
      { label: "C", text: "Meteorologie" },
      { label: "D", text: "Metereology" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 81,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitution for: 'A general pardon granted by a government'.",
    options: [
      { label: "A", text: "Amnesty" },
      { label: "B", text: "Reprieve" },
      { label: "C", text: "Clemency" },
      { label: "D", text: "Parole" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 82,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitute for: 'A secret or disguised way of writing'.",
    options: [
      { label: "A", text: "Cipher" },
      { label: "B", text: "Epistle" },
      { label: "C", text: "Diatribe" },
      { label: "D", text: "Manuscript" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 83,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct phrasal verb:\nThe issue was so delicate that she chose to ____ it altogether.",
    options: [
      { label: "A", text: "brush aside" },
      { label: "B", text: "walk into" },
      { label: "C", text: "shy away from" },
      { label: "D", text: "lean over" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 84,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the correct option:\nThe artifact was notable not merely for its age but also for the ___ with which it was preserved.",
    options: [
      { label: "A", text: "meticulousness" },
      { label: "B", text: "velocity" },
      { label: "C", text: "brevity" },
      { label: "D", text: "severity" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 85,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nThe company needs a detailed feedback (1)/ from all departments (2)/ before finalising its restructuring plan (3)/ for the upcoming fiscal year. (4)/",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 86,
    part: "D",
    partName: "English Comprehension",
    questionText: "Change the following from active to passive:\nThe team will be revising the algorithms during the workshop.",
    options: [
      { label: "A", text: "The algorithms were being revised during the workshop." },
      { label: "B", text: "The algorithms will be been revised during the workshop." },
      { label: "C", text: "The algorithms will be revised during the workshop." },
      { label: "D", text: "The algorithms will be being revised during the workshop." },
    ],
    correctOption: "D",
  },
  {
    questionNo: 87,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nNot only the minister but also the bureaucrats (1)/ has been accused of manipulating (2)/ the data presented in the economic survey (3)/ to align with political interests. (4)",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 88,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the sentence containing the homonym of the highlighted word:\nThe architect discussed the **vault** beneath the cathedral.",
    options: [
      { label: "A", text: "The gymnast performed a perfect vault over the horse." },
      { label: "B", text: "The treasury vault was secured with biometric locks." },
      { label: "C", text: "The earthquake cracked the stone vault supporting the nave." },
      { label: "D", text: "The nobles were interred in the family vault." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 89,
    part: "D",
    partName: "English Comprehension",
    questionText: "Convert the sentence provided below from its passive voice structure to an active voice structure:\nThe children were made to apologize by the principal for their behavior.",
    options: [
      { label: "A", text: "The principal was made to apologize to the children." },
      { label: "B", text: "The principal had made the children apologize." },
      { label: "C", text: "The principal made the children apologize for their behavior." },
      { label: "D", text: "The principal was apologizing to the children for their behavior." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 90,
    part: "D",
    partName: "English Comprehension",
    questionText: "What is the tone of the passage?",
    options: [
      { label: "A", text: "Didactic" },
      { label: "B", text: "Celebratory" },
      { label: "C", text: "Analytical" },
      { label: "D", text: "Flippant" },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 91,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which of the following best illustrates a paradox mentioned in the passage?",
    options: [
      { label: "A", text: "Technology enables cross-cultural empathy." },
      { label: "B", text: "Emojis unify people emotionally across cultures." },
      { label: "C", text: "Fluency in language can still lead to miscommunication." },
      { label: "D", text: "Humor is universally interpreted." },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 92,
    part: "D",
    partName: "English Comprehension",
    questionText: 'The phrase "semiotic dissonance" most likely refers to:',
    options: [
      { label: "A", text: "Discord in musical structure." },
      { label: "B", text: "Misinterpretation of cultural symbols and signs." },
      { label: "C", text: "Breakdown in Wi-Fi or digital signals." },
      { label: "D", text: "Agreement over symbolic meaning." },
    ],
    correctOption: "B",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 93,
    part: "D",
    partName: "English Comprehension",
    questionText: "Why might technology worsen intercultural communication, as per the author?",
    options: [
      { label: "A", text: "It amplifies real-time interaction." },
      { label: "B", text: "It removes the need for shared language." },
      { label: "C", text: "It flattens important non-verbal cues and misrepresents meaning." },
      { label: "D", text: "It encourages spontaneous expression." },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 94,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which of the following metaphors best captures the overall argument of the passage?",
    options: [
      { label: "A", text: "A bridge that never meets the other side." },
      { label: "B", text: "A mirror reflecting only half the image." },
      { label: "C", text: "A labyrinth filled with shifting doors." },
      { label: "D", text: "A ladder leading to one clear peak." },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 95,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nWe **enjoyed very much** at the party.",
    options: [
      { label: "A", text: "have enjoyed very much" },
      { label: "B", text: "enjoyed ourselves very much" },
      { label: "C", text: "enjoyed at the party" },
      { label: "D", text: "were enjoyed" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 96,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nNeither the manager nor the employees **was available**.",
    options: [
      { label: "A", text: "was not available" },
      { label: "B", text: "were also available" },
      { label: "C", text: "were available" },
      { label: "D", text: "was also not available" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 97,
    part: "D",
    partName: "English Comprehension",
    questionText: 'A sentence is provided in direct speech. From the four given options, choose the one that most accurately conveys the sentence in its corresponding indirect speech.\nShe said, "I can solve this problem."',
    options: [
      { label: "A", text: "She said that she will solve that problem." },
      { label: "B", text: "She said that she could solve this problem." },
      { label: "C", text: "She said that she could solve that problem." },
      { label: "D", text: "She said she can solve the problem." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 98,
    part: "D",
    partName: "English Comprehension",
    questionText: "A sentence is provided in indirect speech. From the four given options, choose the one that most accurately conveys the sentence in its corresponding direct speech.\nShe said that she used to play the violin when she was young.",
    options: [
      { label: "A", text: '"I played the violin when I was young," she said.' },
      { label: "B", text: '"I use to play the violin when I was young," she said.' },
      { label: "C", text: '"I used to play the violin when I was young," she said.' },
      { label: "D", text: '"I was playing the violin when I was young," she said.' },
    ],
    correctOption: "C",
  },
  {
    questionNo: 99,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. This is especially useful in software development, where multiple programmers can work on the same codebase simultaneously without conflict.\n2. Version control is a system that records changes to a file or set of files over time so that you can recall specific versions later.\n3. The process involves a specific set of tools and commands that allow for the manipulation and tracking of changes.\n4. By using version control, a project can maintain a complete history of its development, allowing for easy rollback and collaboration.",
    options: [
      { label: "A", text: "2, 4, 3, 1" },
      { label: "B", text: "2, 3, 4, 1" },
      { label: "C", text: "3, 2, 4, 1" },
      { label: "D", text: "4, 1, 2, 3" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 100,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. However, the benefits of reading extend beyond just knowledge acquisition.\n2. Reading is one of the most fundamental skills that a person can develop.\n3. It also improves concentration, analytical thinking, and vocabulary.\n4. From an early age, children who are encouraged to read tend to perform better academically.",
    options: [
      { label: "A", text: "2, 4, 1, 3" },
      { label: "B", text: "2, 1, 4, 3" },
      { label: "C", text: "4, 2, 1, 3" },
      { label: "D", text: "1, 3, 2, 4" },
    ],
    correctOption: "A",
  },
];

// =====================================================================
// 15th September 2025 — Shift 1
// =====================================================================

const PASSAGE_15SEP_90_94 = `The decline of the Indus Valley Civilization, one of the world's earliest urban societies, remains a subject of intense scholarly debate. Flourishing between approximately 3300 BCE and 1300 BCE across what is now Pakistan and northwest India, this civilization demonstrated remarkable feats of urban planning, including grid-patterned streets, advanced drainage systems, and standardized weights and measures. Cities like Mohenjo-daro and Harappa housed populations estimated in the tens of thousands, sustained by a sophisticated agricultural economy and extensive trade networks reaching Mesopotamia. However, by 1900 BCE, signs of urban deterioration became evident—declining construction quality, reduced trade activity, and apparent population dispersal. Several hypotheses have been proposed to explain this collapse. The Aryan Invasion Theory, once dominant, posited that nomadic Indo-European tribes conquered the civilization. However, this theory has been largely discredited due to lack of archaeological evidence of large-scale warfare. Climate change theories suggest that shifting monsoon patterns reduced rainfall, causing rivers—particularly the Ghaggar-Hakra, identified by some scholars with the legendary Saraswati—to dry up or change course. Tectonic activity may have altered river systems, devastating agriculture and urban water supply. Additionally, some researchers point to evidence of flooding, possibly caused by tectonic uplift blocking river drainage. The most contemporary scholarship favors a multicausal model: a confluence of environmental degradation, hydrological changes, economic disruption, and possible epidemic disease gradually eroded the civilization's urban foundations, leading not to a catastrophic collapse but to a protracted de-urbanization and cultural transformation into the subsequent Cemetery H and Painted Grey Ware cultures. The legacy of the Indus Valley Civilization persists in South Asian culture, from town planning principles to aspects of religious iconography.`;

const paper15Sep: QuestionData[] = [
  // ===== PART A: General Intelligence and Reasoning (Q.1-Q.25) =====
  {
    questionNo: 1,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series:\nACE, FHJ, KMO, ?",
    options: [
      { label: "A", text: "PRT" },
      { label: "B", text: "PRU" },
      { label: "C", text: "QSU" },
      { label: "D", text: "PSU" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 2,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In a certain code language, 'MOBILE' is coded as 'OQDKNG'. How will 'TABLET' be coded in the same language?",
    options: [
      { label: "A", text: "VCDNGV" },
      { label: "B", text: "VCDNFV" },
      { label: "C", text: "VCFNGV" },
      { label: "D", text: "VCDNGW" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 3,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out:\n27, 64, 125, __(144)__, 343",
    options: [
      { label: "A", text: "27" },
      { label: "B", text: "64" },
      { label: "C", text: "144" },
      { label: "D", text: "343" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 4,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If '+' means '×', '−' means '÷', '×' means '+', and '÷' means '−', then find the value of:\n8 + 3 × 4 − 2 ÷ 1 = ?",
    options: [
      { label: "A", text: "27" },
      { label: "B", text: "25" },
      { label: "C", text: "29" },
      { label: "D", text: "26" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 5,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Complete the series:\n2, 6, 12, 20, 30, ?",
    options: [
      { label: "A", text: "40" },
      { label: "B", text: "42" },
      { label: "C", text: "44" },
      { label: "D", text: "38" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 6,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'How many triangles are present in the given figure?\n(A square with both diagonals drawn)',
    options: [
      { label: "A", text: "4" },
      { label: "B", text: "6" },
      { label: "C", text: "8" },
      { label: "D", text: "10" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 7,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "A is the mother of B. B is the sister of C. D is the father of C. How is A related to D?",
    options: [
      { label: "A", text: "Mother" },
      { label: "B", text: "Wife" },
      { label: "C", text: "Sister" },
      { label: "D", text: "Daughter" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 8,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the number from among the given options that can replace the question mark (?) in the following series:\n3, 9, 27, 81, ?",
    options: [
      { label: "A", text: "162" },
      { label: "B", text: "243" },
      { label: "C", text: "189" },
      { label: "D", text: "216" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 9,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Read the following statements carefully and identify the conclusion that follows.\nStatements:\nAll roses are flowers.\nSome flowers are red.\nConclusions:\nI. Some roses are red.\nII. Some red things are flowers.",
    options: [
      { label: "A", text: "Only Conclusion I follows" },
      { label: "B", text: "Only Conclusion II follows" },
      { label: "C", text: "Both I and II follow" },
      { label: "D", text: "Neither I nor II follows" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 10,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In a row of students, Ravi is 15th from the left end and 20th from the right end. How many students are there in the row?",
    options: [
      { label: "A", text: "33" },
      { label: "B", text: "34" },
      { label: "C", text: "35" },
      { label: "D", text: "36" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 11,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If CERTAIN is coded as DFSUBJO, how is PRIVATE coded?",
    options: [
      { label: "A", text: "QSJWBUF" },
      { label: "B", text: "QSJWBUE" },
      { label: "C", text: "QSJWCUF" },
      { label: "D", text: "RSJWBUF" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 12,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the option that is related to the third number in the same way as the second number is related to the first number:\n8 : 72 :: 6 : ?",
    options: [
      { label: "A", text: "30" },
      { label: "B", text: "40" },
      { label: "C", text: "36" },
      { label: "D", text: "42" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 13,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Identify the assumptions that must hold for the statement to be valid.\nStatement: The government has decided to ban single-use plastics across all states.\nAssumptions:\nI. Single-use plastics cause significant environmental damage.\nII. Alternative materials are available.\nIII. All citizens support the ban.",
    options: [
      { label: "A", text: "Only I and II are implicit" },
      { label: "B", text: "Only II and III are implicit" },
      { label: "C", text: "Only I is implicit" },
      { label: "D", text: "All I, II and III are implicit" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 14,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following alternative will fill the blanks?\na_bc_ab_ca_c",
    options: [
      { label: "A", text: "b, a, c, b" },
      { label: "B", text: "a, b, c, a" },
      { label: "C", text: "b, c, a, b" },
      { label: "D", text: "c, a, b, b" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 15,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Pointing to a woman, Ramesh said, "Her mother is the only daughter of my mother." How is the woman related to Ramesh?',
    options: [
      { label: "A", text: "Sister" },
      { label: "B", text: "Mother" },
      { label: "C", text: "Niece" },
      { label: "D", text: "Daughter" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 16,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 6 * 3 = 45, 8 * 2 = 68, then 5 * 4 = ?\n(Hint: a * b = a² + b²)",
    options: [
      { label: "A", text: "40" },
      { label: "B", text: "41" },
      { label: "C", text: "42" },
      { label: "D", text: "45" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 17,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "From the given answer figures, select the one that is the mirror image of the given figure when the mirror is placed at the right side.\nFigure: dqbp",
    options: [
      { label: "A", text: "pbqd" },
      { label: "B", text: "bpqd" },
      { label: "C", text: "qdbp" },
      { label: "D", text: "bdpq" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 18,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 'SEND' is coded as 54, and 'CARE' is coded as 26, then what is the code for 'HELP'?",
    options: [
      { label: "A", text: "38" },
      { label: "B", text: "42" },
      { label: "C", text: "40" },
      { label: "D", text: "36" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 19,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out:\nPainter, Sculptor, Architect, Engineer",
    options: [
      { label: "A", text: "Painter" },
      { label: "B", text: "Sculptor" },
      { label: "C", text: "Architect" },
      { label: "D", text: "Engineer" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 20,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If '÷' means '+', '×' means '−', '+' means '×', and '−' means '÷', then find the value of:\n18 − 6 + 2 ÷ 5 × 4 = ?",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "11" },
      { label: "C", text: "9" },
      { label: "D", text: "5" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 21,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Choose the address that is exactly the same as the one given below.\n4/B, Krishna Kunj, M.G. Road, Vashi, Navi Mumbai – 400703",
    options: [
      { label: "A", text: "4/B, Krishna Kunj, M.G. Road, Vashi, Navi Mumbai – 400703" },
      { label: "B", text: "4/B, Krshna Kunj, M.G. Road, Vashi, Navi Mumbai – 400703" },
      { label: "C", text: "4/B, Krishna Kunj, M.G. Road, Vashi, Navi Mumbai – 400730" },
      { label: "D", text: "4/B, Krishna Kunj, M.G. Road, Vasai, Navi Mumbai – 400703" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 22,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In a Venn diagram, if Circle A represents doctors, Circle B represents females, and Circle C represents Indians, then what does the region common to all three circles represent?",
    options: [
      { label: "A", text: "Indian female doctors" },
      { label: "B", text: "Female doctors who are not Indian" },
      { label: "C", text: "Indian doctors who are not female" },
      { label: "D", text: "Females who are neither doctors nor Indian" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 23,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Study the following arrangement of letters and answer the question:\nB E A C D F B D A E C F A B E D\nHow many such A's are there which are immediately preceded by D and immediately followed by E?",
    options: [
      { label: "A", text: "None" },
      { label: "B", text: "One" },
      { label: "C", text: "Two" },
      { label: "D", text: "Three" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 24,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Mohan walks 10 km towards North, turns right and walks 5 km, turns right and walks 10 km. How far and in which direction is he from his starting point?",
    options: [
      { label: "A", text: "5 km East" },
      { label: "B", text: "10 km North" },
      { label: "C", text: "5 km West" },
      { label: "D", text: "10 km East" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 25,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'How many meaningful English words can be formed using the 1st, 3rd, 5th, and 7th letters of the word "SHOULDER", using each letter only once?',
    options: [
      { label: "A", text: "None" },
      { label: "B", text: "One" },
      { label: "C", text: "Two" },
      { label: "D", text: "Three" },
    ],
    correctOption: "C",
  },

  // ===== PART B: General Awareness (Q.26-Q.50) =====
  {
    questionNo: 26,
    part: "B",
    partName: "General Awareness",
    questionText: "The Battle of Plassey was fought in which year?",
    options: [
      { label: "A", text: "1764" },
      { label: "B", text: "1757" },
      { label: "C", text: "1761" },
      { label: "D", text: "1775" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 27,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Fundamental Right is guaranteed under Article 21 of the Indian Constitution?",
    options: [
      { label: "A", text: "Right to Equality" },
      { label: "B", text: "Right to Freedom of Religion" },
      { label: "C", text: "Right to Life and Personal Liberty" },
      { label: "D", text: "Right against Exploitation" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 28,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following is the largest freshwater lake in India?",
    options: [
      { label: "A", text: "Chilika Lake" },
      { label: "B", text: "Dal Lake" },
      { label: "C", text: "Wular Lake" },
      { label: "D", text: "Loktak Lake" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 29,
    part: "B",
    partName: "General Awareness",
    questionText: "What is the chemical formula of baking soda?",
    options: [
      { label: "A", text: "Na₂CO₃" },
      { label: "B", text: "NaHCO₃" },
      { label: "C", text: "NaOH" },
      { label: "D", text: "CaCO₃" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 30,
    part: "B",
    partName: "General Awareness",
    questionText: "Who is known as the 'Father of the Indian Constitution'?",
    options: [
      { label: "A", text: "Jawaharlal Nehru" },
      { label: "B", text: "Mahatma Gandhi" },
      { label: "C", text: "B.R. Ambedkar" },
      { label: "D", text: "Vallabhbhai Patel" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 31,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Indian state has the longest coastline?",
    options: [
      { label: "A", text: "Tamil Nadu" },
      { label: "B", text: "Gujarat" },
      { label: "C", text: "Maharashtra" },
      { label: "D", text: "Andhra Pradesh" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 32,
    part: "B",
    partName: "General Awareness",
    questionText: "The 'Quit India Movement' was launched in which year?",
    options: [
      { label: "A", text: "1940" },
      { label: "B", text: "1941" },
      { label: "C", text: "1942" },
      { label: "D", text: "1943" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 33,
    part: "B",
    partName: "General Awareness",
    questionText: "Which vitamin is produced in the human body upon exposure to sunlight?",
    options: [
      { label: "A", text: "Vitamin A" },
      { label: "B", text: "Vitamin B12" },
      { label: "C", text: "Vitamin C" },
      { label: "D", text: "Vitamin D" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 34,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the following statements:\n1. The Rajya Sabha is a permanent body and is not subject to dissolution.\n2. One-third of its members retire every two years.\nWhich of the above statements is/are correct?",
    options: [
      { label: "A", text: "Only 1" },
      { label: "B", text: "Only 2" },
      { label: "C", text: "Both 1 and 2" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 35,
    part: "B",
    partName: "General Awareness",
    questionText: "The Chipko Movement is associated with the conservation of which natural resource?",
    options: [
      { label: "A", text: "Water" },
      { label: "B", text: "Forests" },
      { label: "C", text: "Wildlife" },
      { label: "D", text: "Soil" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 36,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Indian classical dance form originated in Tamil Nadu?",
    options: [
      { label: "A", text: "Kathak" },
      { label: "B", text: "Bharatanatyam" },
      { label: "C", text: "Odissi" },
      { label: "D", text: "Kuchipudi" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 37,
    part: "B",
    partName: "General Awareness",
    questionText: "The currency of Japan is:",
    options: [
      { label: "A", text: "Yuan" },
      { label: "B", text: "Won" },
      { label: "C", text: "Yen" },
      { label: "D", text: "Ringgit" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 38,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the below statements marked as Assertion (A) and Reason (R). Mark the correct option.\nAssertion (A): The ozone layer protects the Earth from harmful ultraviolet radiation.\nReason (R): Ozone (O₃) absorbs UV-B radiation from the Sun.",
    options: [
      { label: "A", text: "Both A and R are true, and R is the correct explanation of A" },
      { label: "B", text: "Both A and R are true, but R is not the correct explanation of A" },
      { label: "C", text: "A is true, but R is false" },
      { label: "D", text: "A is false, but R is true" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 39,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following rivers does NOT originate in India?",
    options: [
      { label: "A", text: "Ganga" },
      { label: "B", text: "Brahmaputra" },
      { label: "C", text: "Godavari" },
      { label: "D", text: "Narmada" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 40,
    part: "B",
    partName: "General Awareness",
    questionText: "The first session of the Indian National Congress was held in which city?",
    options: [
      { label: "A", text: "Calcutta" },
      { label: "B", text: "Bombay" },
      { label: "C", text: "Madras" },
      { label: "D", text: "Allahabad" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 41,
    part: "B",
    partName: "General Awareness",
    questionText: "Which organ of the human body is primarily responsible for detoxification?",
    options: [
      { label: "A", text: "Kidney" },
      { label: "B", text: "Heart" },
      { label: "C", text: "Liver" },
      { label: "D", text: "Lungs" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 42,
    part: "B",
    partName: "General Awareness",
    questionText: "The Panchayati Raj system in India was constitutionalized by which amendment?",
    options: [
      { label: "A", text: "71st Amendment" },
      { label: "B", text: "73rd Amendment" },
      { label: "C", text: "74th Amendment" },
      { label: "D", text: "86th Amendment" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 43,
    part: "B",
    partName: "General Awareness",
    questionText: "Which planet in our solar system is known as the 'Red Planet'?",
    options: [
      { label: "A", text: "Venus" },
      { label: "B", text: "Jupiter" },
      { label: "C", text: "Mars" },
      { label: "D", text: "Saturn" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 44,
    part: "B",
    partName: "General Awareness",
    questionText: "Match the following:\nA. Sarnath – 1. Jainism\nB. Bodh Gaya – 2. First Sermon of Buddha\nC. Pavapuri – 3. Enlightenment of Buddha\nD. Kushinagar – 4. Mahaparinirvana of Buddha",
    options: [
      { label: "A", text: "A→2, B→3, C→1, D→4" },
      { label: "B", text: "A→3, B→2, C→1, D→4" },
      { label: "C", text: "A→2, B→3, C→4, D→1" },
      { label: "D", text: "A→1, B→2, C→3, D→4" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 45,
    part: "B",
    partName: "General Awareness",
    questionText: "Which schedule of the Indian Constitution deals with the allocation of seats in the Rajya Sabha?",
    options: [
      { label: "A", text: "Third Schedule" },
      { label: "B", text: "Fourth Schedule" },
      { label: "C", text: "Seventh Schedule" },
      { label: "D", text: "Eighth Schedule" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 46,
    part: "B",
    partName: "General Awareness",
    questionText: "The SI unit of electric current is:",
    options: [
      { label: "A", text: "Volt" },
      { label: "B", text: "Ohm" },
      { label: "C", text: "Ampere" },
      { label: "D", text: "Watt" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 47,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following is NOT a greenhouse gas?",
    options: [
      { label: "A", text: "Carbon dioxide" },
      { label: "B", text: "Methane" },
      { label: "C", text: "Nitrogen" },
      { label: "D", text: "Nitrous oxide" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 48,
    part: "B",
    partName: "General Awareness",
    questionText: "The famous Sun Temple is located at:",
    options: [
      { label: "A", text: "Puri" },
      { label: "B", text: "Konark" },
      { label: "C", text: "Khajuraho" },
      { label: "D", text: "Madurai" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 49,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the following Assertion (A) and Reason (R) carefully.\nAssertion (A): India follows a parliamentary system of government.\nReason (R): The President of India is the head of state and exercises real executive power.",
    options: [
      { label: "A", text: "Both A and R are true and R is the correct explanation of A" },
      { label: "B", text: "Both A and R are true but R is not the correct explanation of A" },
      { label: "C", text: "A is true but R is false" },
      { label: "D", text: "A is false but R is true" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 50,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Five Year Plan in India gave highest priority to agriculture for the first time?",
    options: [
      { label: "A", text: "First Five Year Plan" },
      { label: "B", text: "Second Five Year Plan" },
      { label: "C", text: "Third Five Year Plan" },
      { label: "D", text: "Fourth Five Year Plan" },
    ],
    correctOption: "A",
  },

  // ===== PART C: Quantitative Aptitude (Q.51-Q.75) =====
  {
    questionNo: 51,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If the ratio of A to B is 3 : 5 and the ratio of B to C is 4 : 7, find the ratio A : B : C.",
    options: [
      { label: "A", text: "12 : 20 : 35" },
      { label: "B", text: "3 : 5 : 7" },
      { label: "C", text: "12 : 20 : 28" },
      { label: "D", text: "15 : 20 : 35" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 52,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A shopkeeper buys an article for ₹400 and marks it at ₹600. He offers a discount of 10%. What is his profit percentage?",
    options: [
      { label: "A", text: "30%" },
      { label: "B", text: "35%" },
      { label: "C", text: "40%" },
      { label: "D", text: "45%" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 53,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A train 200 m long crosses a pole in 10 seconds. What is the speed of the train in km/h?",
    options: [
      { label: "A", text: "60 km/h" },
      { label: "B", text: "72 km/h" },
      { label: "C", text: "80 km/h" },
      { label: "D", text: "90 km/h" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 54,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The average of 5 consecutive even numbers is 16. What is the largest number?",
    options: [
      { label: "A", text: "18" },
      { label: "B", text: "20" },
      { label: "C", text: "22" },
      { label: "D", text: "24" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 55,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A can do a piece of work in 12 days. B can do it in 18 days. In how many days can they complete the work together?",
    options: [
      { label: "A", text: "7.2 days" },
      { label: "B", text: "6 days" },
      { label: "C", text: "8 days" },
      { label: "D", text: "9 days" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 56,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "What is the simple interest on ₹5000 at 8% per annum for 3 years?",
    options: [
      { label: "A", text: "₹1000" },
      { label: "B", text: "₹1200" },
      { label: "C", text: "₹1400" },
      { label: "D", text: "₹1500" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 57,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually, is:",
    options: [
      { label: "A", text: "₹2000" },
      { label: "B", text: "₹2050" },
      { label: "C", text: "₹2100" },
      { label: "D", text: "₹2200" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 58,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If cos θ = 3/5, then find the value of tan θ.",
    options: [
      { label: "A", text: "3/4" },
      { label: "B", text: "4/3" },
      { label: "C", text: "4/5" },
      { label: "D", text: "5/4" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 59,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A mixture of milk and water contains 80% milk. If 4 litres of water is added, the percentage of milk becomes 64%. What was the original quantity of the mixture?",
    options: [
      { label: "A", text: "12 litres" },
      { label: "B", text: "16 litres" },
      { label: "C", text: "20 litres" },
      { label: "D", text: "24 litres" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 60,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The perimeter of a rectangle is 60 cm and its length is twice its breadth. Find the area of the rectangle.",
    options: [
      { label: "A", text: "150 cm²" },
      { label: "B", text: "200 cm²" },
      { label: "C", text: "250 cm²" },
      { label: "D", text: "300 cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 61,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A cylindrical tank has a radius of 7 cm and height of 10 cm. What is its volume? (Use π = 22/7)",
    options: [
      { label: "A", text: "1540 cm³" },
      { label: "B", text: "1440 cm³" },
      { label: "C", text: "1340 cm³" },
      { label: "D", text: "1640 cm³" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 62,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two pipes A and B can fill a tank in 12 hours and 15 hours respectively. If both pipes are opened together, how long will it take to fill the tank?",
    options: [
      { label: "A", text: "6 hours" },
      { label: "B", text: "6 hours 40 minutes" },
      { label: "C", text: "7 hours" },
      { label: "D", text: "7 hours 30 minutes" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 63,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If x + 1/x = 5, then find the value of x² + 1/x².",
    options: [
      { label: "A", text: "21" },
      { label: "B", text: "23" },
      { label: "C", text: "25" },
      { label: "D", text: "27" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 64,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The HCF of two numbers is 12 and their LCM is 360. If one of the numbers is 60, what is the other number?",
    options: [
      { label: "A", text: "72" },
      { label: "B", text: "84" },
      { label: "C", text: "60" },
      { label: "D", text: "48" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 65,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A boat goes 24 km upstream in 6 hours and 24 km downstream in 4 hours. Find the speed of the boat in still water.",
    options: [
      { label: "A", text: "4 km/h" },
      { label: "B", text: "5 km/h" },
      { label: "C", text: "6 km/h" },
      { label: "D", text: "7 km/h" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 66,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "In a triangle, if one angle is 90° and one of the other angles is 45°, what is the ratio of the two legs?",
    options: [
      { label: "A", text: "1 : 1" },
      { label: "B", text: "1 : √2" },
      { label: "C", text: "1 : √3" },
      { label: "D", text: "√3 : 1" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 67,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: (√50 + √32) ÷ √2",
    options: [
      { label: "A", text: "7" },
      { label: "B", text: "9" },
      { label: "C", text: "11" },
      { label: "D", text: "13" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 68,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The total surface area of a cube is 294 cm². What is the volume of the cube?",
    options: [
      { label: "A", text: "343 cm³" },
      { label: "B", text: "216 cm³" },
      { label: "C", text: "512 cm³" },
      { label: "D", text: "125 cm³" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 69,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "An article is sold for ₹1440 after giving two successive discounts of 10% and 20% on the marked price. Find the marked price.",
    options: [
      { label: "A", text: "₹1800" },
      { label: "B", text: "₹1900" },
      { label: "C", text: "₹2000" },
      { label: "D", text: "₹2100" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 70,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The diagonal of a square is 10√2 cm. What is the area of the square?",
    options: [
      { label: "A", text: "50 cm²" },
      { label: "B", text: "100 cm²" },
      { label: "C", text: "200 cm²" },
      { label: "D", text: "150 cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 71,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If the selling price is doubled, the profit triples. What is the ratio of cost price to selling price?",
    options: [
      { label: "A", text: "1 : 2" },
      { label: "B", text: "2 : 3" },
      { label: "C", text: "3 : 4" },
      { label: "D", text: "1 : 3" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 72,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The circumference of a circle is 44 cm. What is its area? (Use π = 22/7)",
    options: [
      { label: "A", text: "154 cm²" },
      { label: "B", text: "144 cm²" },
      { label: "C", text: "132 cm²" },
      { label: "D", text: "176 cm²" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 73,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A chord of length 16 cm is at a distance of 6 cm from the center of a circle. What is the radius of the circle?",
    options: [
      { label: "A", text: "8 cm" },
      { label: "B", text: "10 cm" },
      { label: "C", text: "12 cm" },
      { label: "D", text: "14 cm" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 74,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "In a pie chart representing expenses, if 'Food' has a central angle of 120°, what percentage of total expenses does food represent?",
    options: [
      { label: "A", text: "25%" },
      { label: "B", text: "30%" },
      { label: "C", text: "33.33%" },
      { label: "D", text: "40%" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 75,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A man invests ₹12,000 at compound interest at 5% per annum. What will be the amount after 2 years?",
    options: [
      { label: "A", text: "₹13,200" },
      { label: "B", text: "₹13,230" },
      { label: "C", text: "₹13,000" },
      { label: "D", text: "₹13,500" },
    ],
    correctOption: "B",
  },

  // ===== PART D: English Comprehension (Q.76-Q.100) =====
  {
    questionNo: 76,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate synonym of the given word: **BENEVOLENT**",
    options: [
      { label: "A", text: "Kind" },
      { label: "B", text: "Hostile" },
      { label: "C", text: "Jealous" },
      { label: "D", text: "Selfish" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 77,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: **EPHEMERAL**",
    options: [
      { label: "A", text: "Temporary" },
      { label: "B", text: "Permanent" },
      { label: "C", text: "Fleeting" },
      { label: "D", text: "Brief" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 78,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct meaning of the idiom:\n**Burn the midnight oil**",
    options: [
      { label: "A", text: "To waste resources" },
      { label: "B", text: "To work or study late into the night" },
      { label: "C", text: "To light a fire" },
      { label: "D", text: "To destroy evidence" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 79,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: **VERBOSE**",
    options: [
      { label: "A", text: "Concise" },
      { label: "B", text: "Wordy" },
      { label: "C", text: "Lengthy" },
      { label: "D", text: "Detailed" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 80,
    part: "D",
    partName: "English Comprehension",
    questionText: "Identify the correctly spelt word:",
    options: [
      { label: "A", text: "Accomodation" },
      { label: "B", text: "Accommodation" },
      { label: "C", text: "Acommodation" },
      { label: "D", text: "Acomodation" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 81,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitution for: 'A person who speaks many languages'.",
    options: [
      { label: "A", text: "Polyglot" },
      { label: "B", text: "Linguist" },
      { label: "C", text: "Philologist" },
      { label: "D", text: "Interpreter" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 82,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitution for: 'Government by the wealthy'.",
    options: [
      { label: "A", text: "Democracy" },
      { label: "B", text: "Theocracy" },
      { label: "C", text: "Plutocracy" },
      { label: "D", text: "Aristocracy" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 83,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct phrasal verb to fill in the blank:\nThe meeting has been **____** to next Monday.",
    options: [
      { label: "A", text: "put off" },
      { label: "B", text: "put up" },
      { label: "C", text: "put down" },
      { label: "D", text: "put out" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 84,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the correct option to fill in the blank:\nThe committee members could not arrive at a ______ on the matter.",
    options: [
      { label: "A", text: "consensus" },
      { label: "B", text: "consciences" },
      { label: "C", text: "consciousness" },
      { label: "D", text: "census" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 85,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\n**Each of the boys** (1) / **have completed** (2) / **their assignments** (3) / **before the deadline.** (4)",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 86,
    part: "D",
    partName: "English Comprehension",
    questionText: "Change the following from active to passive voice:\nThe teacher is teaching the students grammar.",
    options: [
      { label: "A", text: "The students are being taught grammar by the teacher." },
      { label: "B", text: "Grammar is taught to the students by the teacher." },
      { label: "C", text: "The students were being taught grammar by the teacher." },
      { label: "D", text: "Grammar has been taught to the students by the teacher." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 87,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\n**The sceneries of** (1) / **Kashmir are** (2) / **so beautiful that** (3) / **tourists flock there every year.** (4)",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 88,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the sentence containing the homonym of the highlighted word:\nHe placed the **bat** on the table.",
    options: [
      { label: "A", text: "A bat flew out of the cave at dusk." },
      { label: "B", text: "He swung the bat hard and hit a six." },
      { label: "C", text: "The cricket bat was made of willow." },
      { label: "D", text: "She bought a new bat for the tournament." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 89,
    part: "D",
    partName: "English Comprehension",
    questionText: "Convert the following from passive to active voice:\nA beautiful song was sung by her at the concert.",
    options: [
      { label: "A", text: "She sang a beautiful song at the concert." },
      { label: "B", text: "She had sung a beautiful song at the concert." },
      { label: "C", text: "She was singing a beautiful song at the concert." },
      { label: "D", text: "She has sung a beautiful song at the concert." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 90,
    part: "D",
    partName: "English Comprehension",
    questionText: "What does the passage primarily discuss?",
    options: [
      { label: "A", text: "The military conquest of the Indus Valley Civilization" },
      { label: "B", text: "The causes and theories behind the decline of the Indus Valley Civilization" },
      { label: "C", text: "The trade networks of Mesopotamia" },
      { label: "D", text: "The architectural achievements of Harappa" },
    ],
    correctOption: "B",
    passage: PASSAGE_15SEP_90_94,
  },
  {
    questionNo: 91,
    part: "D",
    partName: "English Comprehension",
    questionText: "According to the passage, why has the Aryan Invasion Theory been largely discredited?",
    options: [
      { label: "A", text: "Because new DNA evidence proved it wrong" },
      { label: "B", text: "Because there is no archaeological evidence of large-scale warfare" },
      { label: "C", text: "Because the Aryans arrived peacefully" },
      { label: "D", text: "Because the theory was proposed too recently" },
    ],
    correctOption: "B",
    passage: PASSAGE_15SEP_90_94,
  },
  {
    questionNo: 92,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which of the following is mentioned as a possible cause of the civilization's decline?",
    options: [
      { label: "A", text: "Volcanic eruptions" },
      { label: "B", text: "Foreign trade surplus" },
      { label: "C", text: "Shifting monsoon patterns reducing rainfall" },
      { label: "D", text: "Overpopulation in cities" },
    ],
    correctOption: "C",
    passage: PASSAGE_15SEP_90_94,
  },
  {
    questionNo: 93,
    part: "D",
    partName: "English Comprehension",
    questionText: 'What does the phrase **"protracted de-urbanization"** most likely mean in the context of the passage?',
    options: [
      { label: "A", text: "Rapid destruction of cities" },
      { label: "B", text: "A sudden migration to rural areas" },
      { label: "C", text: "A slow and prolonged decline of urban living" },
      { label: "D", text: "An immediate political collapse" },
    ],
    correctOption: "C",
    passage: PASSAGE_15SEP_90_94,
  },
  {
    questionNo: 94,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which model does contemporary scholarship most favor regarding the civilization's decline?",
    options: [
      { label: "A", text: "A single catastrophic event" },
      { label: "B", text: "The Aryan Invasion" },
      { label: "C", text: "A multicausal model involving environmental and economic factors" },
      { label: "D", text: "Epidemic disease as the sole cause" },
    ],
    correctOption: "C",
    passage: PASSAGE_15SEP_90_94,
  },
  {
    questionNo: 95,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nShe **don't know** nothing about the incident.",
    options: [
      { label: "A", text: "doesn't know anything" },
      { label: "B", text: "don't knows nothing" },
      { label: "C", text: "doesn't knows anything" },
      { label: "D", text: "don't know anything" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 96,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nHe is one of the **best player** in the team.",
    options: [
      { label: "A", text: "best players" },
      { label: "B", text: "better player" },
      { label: "C", text: "good player" },
      { label: "D", text: "best playing" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 97,
    part: "D",
    partName: "English Comprehension",
    questionText: 'A sentence is provided in direct speech. Choose the one that most accurately conveys it in indirect speech.\nHe said, "I am feeling unwell today."',
    options: [
      { label: "A", text: "He said that he is feeling unwell today." },
      { label: "B", text: "He said that he was feeling unwell that day." },
      { label: "C", text: "He said that he has been feeling unwell today." },
      { label: "D", text: "He said that he felt unwell today." },
    ],
    correctOption: "B",
  },
  {
    questionNo: 98,
    part: "D",
    partName: "English Comprehension",
    questionText: "A sentence is provided in indirect speech. Choose the one that most accurately conveys it in direct speech.\nShe told me that she had finished her homework.",
    options: [
      { label: "A", text: '"I have finished my homework," she told me.' },
      { label: "B", text: '"I had finished my homework," she told me.' },
      { label: "C", text: '"I finished my homework," she told me.' },
      { label: "D", text: '"I will finish my homework," she told me.' },
    ],
    correctOption: "A",
  },
  {
    questionNo: 99,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. It is the foundation upon which all other subjects are built.\n2. Mathematics is often called the queen of sciences.\n3. Without a solid understanding of mathematics, progress in physics, engineering, and computer science would be impossible.\n4. From ancient civilizations to modern technology, mathematics has been central to human advancement.",
    options: [
      { label: "A", text: "2, 1, 4, 3" },
      { label: "B", text: "2, 4, 1, 3" },
      { label: "C", text: "4, 2, 1, 3" },
      { label: "D", text: "1, 2, 3, 4" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 100,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct meaning of the idiom:\n**A penny for your thoughts**",
    options: [
      { label: "A", text: "Asking someone to share what they are thinking" },
      { label: "B", text: "Offering someone money for their ideas" },
      { label: "C", text: "Suggesting that ideas are cheap" },
      { label: "D", text: "Criticizing someone for overthinking" },
    ],
    correctOption: "A",
  },
];

// =====================================================================
// Paper registry
// =====================================================================
export const papers: PaperInfo[] = [
  {
    id: "16-sep-2025-shift-1",
    title: "SSC CGL 16 Sep 2025 (Shift-1)",
    date: "16 Sep 2025",
    shift: "Shift-1 (09:00 AM)",
    questions: paper16Sep,
  },
  {
    id: "15-sep-2025-shift-1",
    title: "SSC CGL 15 Sep 2025 (Shift-1)",
    date: "15 Sep 2025",
    shift: "Shift-1 (09:00 AM)",
    questions: paper15Sep,
  },
];

export const questionsData: QuestionData[] = paper16Sep;
