export interface QuestionData {
  questionNo: number;
  part: string;
  partName: string;
  questionText: string;
  options: { label: string; text: string }[];
  correctOption: string;
  passage?: string;
}

const PASSAGE_90_94 = `In the labyrinth of globalization, where intercontinental dialogues shape diplomacy, business, and social cohesion, the intricate terrain of cross-cultural communication remains one of the most formidable cognitive frontiers. Misunderstandings often arise not from lexical deficiencies but from semiotic dissonance—where gestures, silences, intonations, or proxemics are interpreted through incongruent cultural lenses. The assumption that language fluency equates to communicative efficacy is a pernicious fallacy; in reality, fluency may obfuscate cultural asymmetries, allowing misinterpretation to masquerade as comprehension. In high-context cultures—such as Japan or the Arab world—communication is embedded in relational nuance, tacit implications, and communal hierarchies. Conversely, low-context cultures like Germany or the United States prioritize explicitness, objectivity, and individual clarity. When interlocutors from these paradigms converge, the mismatch can generate diplomatic friction, transactional inefficiency, or interpersonal alienation. Even seemingly innocuous behaviors—eye contact, turn-taking, or humor—can catalyze discomfort when interpreted through a monocultural lens. Furthermore, the cognitive filters individuals deploy—shaped by education, tradition, and sociopolitical conditioning—often reinforce in-group validation while relegating unfamiliar communication styles to categories of deviance or incompetence. This ethnocentric predisposition exacerbates stereotyping, reduces empathetic bandwidth, and curtails the potential for collaborative synergy. Technology, while ostensibly bridging geographic divides, further complicates intercultural interaction. Emojis, for instance, are semantically fluid; a single icon may evoke warmth in one culture and sarcasm in another. Algorithmic translation, lacking context-sensitivity, risks converting diplomatic nuance into semantic absurdity. Even video conferencing flattens paralinguistic cues vital to cross-cultural understanding. Ultimately, transcending these communicative chasms demands metacognitive vigilance, cultural humility, and dialogic adaptability. Effective intercultural communicators do not merely learn linguistic syntax but cultivate cultural empathy, interrogate their own perceptual frameworks, and develop a tolerance for ambiguity. It is within this cognitive dissonance that the richest intercultural growth unfolds—not through the elimination of difference, but through its embrace.`;

export const questionsData: QuestionData[] = [
  // ===== PART A: General Intelligence and Reasoning (Q.1-Q.25) =====
  {
    questionNo: 1,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Sentence: "Reflections are clearer in calm waters." If each letter is mirrored using alphabetical symmetry (A↔Z, B↔Y...), what is the 2nd letter of the 6th word after mirroring?',
    options: [
      { label: "A", text: "d" },
      { label: "B", text: "x" },
      { label: "C", text: "y" },
      { label: "D", text: "z" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 2,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Choose the address that is exactly the same as the one given below.\nFlat 201, Sapphire Tower, Garia Station Rd., Kolkata, West Bengal – 700084",
    options: [
      { label: "A", text: "Flat 201, Saphire Tower, Garia Station Rd., Kolkata, West Bengal – 700084" },
      { label: "B", text: "Flat 201, Sapphire Tower, Garia Station Rd., Kolkata, West Bengal – 700084" },
      { label: "C", text: "Flat 201, Sapphire Tower, Gariya Station Rd., Kolkata, West Bengal – 700084" },
      { label: "D", text: "Flat 201, Sapphire Tower, Garia Station Road, Kolkata, West Bengal – 700084" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 3,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Which of the following alternative will fill the blanks?\nm_u_mg_p_gu_",
    options: [
      { label: "A", text: "g,p,u,m,p" },
      { label: "B", text: "g,p,u,p,m" },
      { label: "C", text: "p,u,u,p,m" },
      { label: "D", text: "p,p,u,m,g" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 4,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Select the letter-cluster from among the given options that can replace the question mark (?) in the following series:\nGBDF, GHMR, GNVD, GTEP, ?",
    options: [
      { label: "A", text: "G Z M B" },
      { label: "B", text: "G Z N C" },
      { label: "C", text: "G Z N B" },
      { label: "D", text: "G Y N B" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 5,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 'Z' denotes 'addition', 'X' denotes 'multiplication', 'Y' denotes 'division', and 'W' denotes 'subtraction', then what will be the value of the following expression?\n3.2 Z (0.56 Y 1.4 X 4) W 5 X 5 Y 25 Z 5.",
    options: [
      { label: "A", text: "6.9" },
      { label: "B", text: "8.8" },
      { label: "C", text: "8.6" },
      { label: "D", text: "9.8" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 6,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out:\nA@1A, B@2B, C@4C, D@4D",
    options: [
      { label: "A", text: "A@1A, B@2B" },
      { label: "B", text: "B@2B, C@4C" },
      { label: "C", text: "C@4C, D@4D" },
      { label: "D", text: "A@1A, D@4D" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 7,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What will come at the place of question mark?\n1, 3, 7, 15, 31, ?",
    options: [
      { label: "A", text: "62" },
      { label: "B", text: "63" },
      { label: "C", text: "64" },
      { label: "D", text: "65" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 8,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Instruction: Identify the assumptions that must hold for the statement to be valid, then choose the correct option.\nStatement: Deforestation in tropical rainforests, primarily driven by agricultural expansion and logging, not only contributes to the loss of biodiversity but also exacerbates global warming by reducing the Earth's capacity to absorb carbon dioxide.\nAssumptions:\nI. Deforestation reduces the Earth's ability to absorb carbon dioxide.\nII. Agricultural expansion and logging are the primary causes of deforestation.\nIII. The loss of biodiversity is the most significant consequence of deforestation.",
    options: [
      { label: "A", text: "Only I and II are implicit" },
      { label: "B", text: "Only II and III are implicit" },
      { label: "C", text: "Only I is implicit" },
      { label: "D", text: "All I, II and III are implicit" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 9,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Read the following statement carefully and identify the conclusion that follows.\nStatement: The city experienced its worst rainfall in 50 years.\nConclusions:\nI. The city's drainage systems may have failed.\nII. Such rainfall occurs regularly.",
    options: [
      { label: "A", text: "Only Conclusion I follows" },
      { label: "B", text: "Only Conclusion II follows" },
      { label: "C", text: "Both I and II follow" },
      { label: "D", text: "Neither I nor II follows" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 10,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'How many meaningful four-letter English words can be formed using the first, second, third, and fifth letters of the word "TRAVEL" (when counted from left to right), using each letter only once in each word?',
    options: [
      { label: "A", text: "One" },
      { label: "B", text: "Three" },
      { label: "C", text: "Two" },
      { label: "D", text: "Five" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 11,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In the following question, a pair of letters is given, followed by its corresponding product of alphabetical positions (A = 1, B = 2, ..., Z = 26). A second pair is given without its product. Identify the correct product for the second pair that maintains the same relationship as the first.\nNxP : 14×16 :: ExI : ?",
    options: [
      { label: "A", text: "5×9" },
      { label: "B", text: "6×9" },
      { label: "C", text: "5×10" },
      { label: "D", text: "6×8" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 12,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Complete the series.\nZ1, Y2, X3, W4, ?",
    options: [
      { label: "A", text: "V5" },
      { label: "B", text: "V4" },
      { label: "C", text: "U5" },
      { label: "D", text: "X5" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 13,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Find the odd one out from the given alternatives:\nArticle 14, Article 19, Article 21, Article 370",
    options: [
      { label: "A", text: "Article 14" },
      { label: "B", text: "Article 19" },
      { label: "C", text: "Article 21" },
      { label: "D", text: "Article 370" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 14,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "A is the daughter of B. B is the son of C. D is the wife of C. How is D related to A?",
    options: [
      { label: "A", text: "Aunt" },
      { label: "B", text: "Mother" },
      { label: "C", text: "Grandmother" },
      { label: "D", text: "Sister" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 15,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 3 + 4 = 19 and 2 + 5 = 17, what is 1 + 6 = ?",
    options: [
      { label: "A", text: "15" },
      { label: "B", text: "13" },
      { label: "C", text: "12" },
      { label: "D", text: "11" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 16,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "In a certain code language, each letter is assigned a unique digit. Based on the given codes for specific words, determine the code for the target word using the same logic.\nIf SPEED is coded as 83551 and COOL is coded as 9226, then how will SCOOP be coded?",
    options: [
      { label: "A", text: "89213" },
      { label: "B", text: "89276" },
      { label: "C", text: "89223" },
      { label: "D", text: "89327" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 17,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 5 * 4 = 41 and 6 * 3 = 45, what is 7 * 2?",
    options: [
      { label: "A", text: "48" },
      { label: "B", text: "51" },
      { label: "C", text: "53" },
      { label: "D", text: "55" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 18,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 'READ' is coded as T2@3, and 'DEAR' is coded as 3@2T, then what is the code for 'DARE'?",
    options: [
      { label: "A", text: "3@T2" },
      { label: "B", text: "T@23" },
      { label: "C", text: "@32T" },
      { label: "D", text: "@32Y" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 19,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "What is the average of 5 consecutive odd numbers starting from 13?",
    options: [
      { label: "A", text: "17" },
      { label: "B", text: "18" },
      { label: "C", text: "20" },
      { label: "D", text: "23" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 20,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If the given symbols mean:\n'+' means 'divided by'\n'-' means 'multiplied by'\n'x' means 'minus'\n'÷' means 'plus'\nThen, find the value of the following expression: 40 x 5 + 8 + 16 - 2=?",
    options: [
      { label: "A", text: "56" },
      { label: "B", text: "27" },
      { label: "C", text: "48" },
      { label: "D", text: "36" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 21,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: 'Pointing to a photograph, a man says, "She is the daughter of the only son of my father\'s wife". Who is the woman to the man?',
    options: [
      { label: "A", text: "Sister" },
      { label: "B", text: "Cousin" },
      { label: "C", text: "Niece" },
      { label: "D", text: "Daughter" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 22,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If 'x' = '+', '÷' = '-', '−' = '÷', '÷' = 'x', which equation is correct?",
    options: [
      { label: "A", text: "10 + 2 × 2 − 4 = 10" },
      { label: "B", text: "14 ÷ 2 − 2 + 4 = 10" },
      { label: "C", text: "12 × 2 + 4 − 1 = 27" },
      { label: "D", text: "8 + 4 − 2 × 1 = 10" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 23,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "Read the following statements and evaluate the conclusions based on traditional syllogistic logic. Consider the statements to be absolutely true, even if they appear contrary to known facts. Determine which conclusion(s) logically follow from the given statements.\nStatements:\nAll metals are elements.\nSome elements are gases.\nConclusions:\nI. Some metals are gases.\nII. All gases being elements is a possibility.",
    options: [
      { label: "A", text: "Only Conclusion II follows" },
      { label: "B", text: "Both I and II follow" },
      { label: "C", text: "Only Conclusion I follows" },
      { label: "D", text: "Neither I nor II follows" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 24,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "If '+' means '×', '−' means '÷', 'x' means '+', then 4 − 2 × 3 + 6 = ?",
    options: [
      { label: "A", text: "12" },
      { label: "B", text: "6" },
      { label: "C", text: "5" },
      { label: "D", text: "20" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 25,
    part: "A",
    partName: "General Intelligence and Reasoning",
    questionText: "The ratio of two numbers is 4:5 and their sum is 180. Find the numbers.",
    options: [
      { label: "A", text: "60 and 75" },
      { label: "B", text: "72 and 108" },
      { label: "C", text: "80 and 100" },
      { label: "D", text: "64 and 116" },
    ],
    correctOption: "C",
  },

  // ===== PART B: General Awareness (Q.26-Q.50) =====
  {
    questionNo: 26,
    part: "B",
    partName: "General Awareness",
    questionText: "What feature was used on Golconda Fort's gates to protect it during attacks involving war elephants?",
    options: [
      { label: "A", text: "Deep moat with water channels" },
      { label: "B", text: "Electrified spikes" },
      { label: "C", text: "Steel spikes on doors" },
      { label: "D", text: "Stone cannon towers" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 27,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following best captures the core rituals and symbolism of the Fagli (Kus/Kuns) festival in Pattan Valley?",
    options: [
      { label: "A", text: "Baraza, symbolizing Shikhara-Appa, is made with marigold and turmeric and placed at village shrines." },
      { label: "B", text: "Punha involves symbolic ploughing indoors using willow sticks, reflecting farming hopes during snow." },
      { label: "C", text: "Totu, made of wheat and honey, is offered on rooftops to priests, then fed to goats." },
      { label: "D", text: "Kwari sweets are made by elder women for temple offerings, as men chant to crow spirits." },
    ],
    correctOption: "B",
  },
  {
    questionNo: 28,
    part: "B",
    partName: "General Awareness",
    questionText: "Determine the correctly matched Gupta fiscal term with its meaning.",
    options: [
      { label: "A", text: "Hiranya – compulsory labour service" },
      { label: "B", text: "Dhanya – gold tax" },
      { label: "C", text: "Bhoga – king's share of produce" },
      { label: "D", text: "Vaishthika – forced or corvée labour" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 29,
    part: "B",
    partName: "General Awareness",
    questionText: "Which musical instrument from Sikkim is believed to have been the first created for the deity Tetlara Lahadongna, and is associated with mythological origins?",
    options: [
      { label: "A", text: "Niyara Hongsing Ke" },
      { label: "B", text: "Simikla Koom (Binayo)" },
      { label: "C", text: "Yema Dhol" },
      { label: "D", text: "Nagara of Yeba" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 30,
    part: "B",
    partName: "General Awareness",
    questionText: "Karnam Malleswari became the first Indian woman to win an Olympic medal in which sporting discipline?",
    options: [
      { label: "A", text: "Boxing" },
      { label: "B", text: "Athletics" },
      { label: "C", text: "Weightlifting" },
      { label: "D", text: "Long Jump" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 31,
    part: "B",
    partName: "General Awareness",
    questionText: "Match each ruler listed in Column A with their respective period of reign given in Column B:\nA. Qutbuddin Aybak – 1. 1175-1192\nB. Prithviraj Chauhan – 2. 1206-1210\nC. Alauddin Khalji – 3. 1296-1316\nD. Muhammad Tughluq – 4. 1324-1351",
    options: [
      { label: "A", text: "A→1, B→2, C→3, D→4" },
      { label: "B", text: "A→4, B→1, C→3, D→2" },
      { label: "C", text: "A→3, B→1, C→2, D→4" },
      { label: "D", text: "A→2, B→1, C→3, D→4" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 32,
    part: "B",
    partName: "General Awareness",
    questionText: "Fill in the blanks:\nAt the 1984 Summer Olympics, P. T. Usha narrowly missed a bronze medal by ________ of a second.",
    options: [
      { label: "A", text: "One-hundredth" },
      { label: "B", text: "One-tenth" },
      { label: "C", text: "One-thousandth" },
      { label: "D", text: "One-fiftyth" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 33,
    part: "B",
    partName: "General Awareness",
    questionText: "Fill in the Blank:\nDuring India's BRICS Chairship in 2021, key initiatives included the Digital Health Summit and the _____ for environmental cooperation.",
    options: [
      { label: "A", text: "BRICS Water Security Pact" },
      { label: "B", text: "BRICS Alliance for Green Tourism" },
      { label: "C", text: "BRICS Climate Finance Agreement" },
      { label: "D", text: "BRICS Sustainable Energy Forum" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 34,
    part: "B",
    partName: "General Awareness",
    questionText: "Who wrote 'Indica: A Deep Natural History of the Indian Subcontinent'?",
    options: [
      { label: "A", text: "Sanjeev Sanyal" },
      { label: "B", text: "Pranay Lal" },
      { label: "C", text: "Rohan Murty" },
      { label: "D", text: "Tony Joseph" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 35,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following about the men's hockey event at the 38th National Games 2025 is/are correct?\n1.) Karnataka beat Uttar Pradesh 3-2 in the final.\n2.) Karnataka vs Maharashtra semifinal ended 2-2, decided by shootout.\n3.) Punjab won bronze by defeating Maharashtra 1-0.",
    options: [
      { label: "A", text: "Both 1 and 2 are correct" },
      { label: "B", text: "Both 1 and 3 are correct" },
      { label: "C", text: "Both 2 and 3 are correct" },
      { label: "D", text: "1, 2 and 3 all are correct" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 36,
    part: "B",
    partName: "General Awareness",
    questionText: "What initiative did Dr. Jitendra Singh launch in May 2025 as MoS PMO and MoS Personnel?",
    options: [
      { label: "A", text: "National Grievance Redress Portal" },
      { label: "B", text: "e-Civil List 2025 e-book" },
      { label: "C", text: "Central Police Commemoration Day" },
      { label: "D", text: "Digital Land Records Survey" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 37,
    part: "B",
    partName: "General Awareness",
    questionText: "Uttar Pradesh accounted for approximately what percent of India's total population in 2011?",
    options: [
      { label: "A", text: "10%" },
      { label: "B", text: "12%" },
      { label: "C", text: "16%" },
      { label: "D", text: "18%" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 38,
    part: "B",
    partName: "General Awareness",
    questionText: "What does the designation HLVM3 stand for in the Gaganyaan mission context?",
    options: [
      { label: "A", text: "Heavy LVM3" },
      { label: "B", text: "Hybrid LVM3" },
      { label: "C", text: "Human LVM3" },
      { label: "D", text: "High LVM3" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 39,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following minerals is found in large quantities in India and holds high economic importance?",
    options: [
      { label: "A", text: "Copper" },
      { label: "B", text: "Petroleum" },
      { label: "C", text: "Iron ore" },
      { label: "D", text: "Tin" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 40,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the following statements:\n1) Both the Prime Minister (PM) and Chief Minister (CM) can advise dissolution of the respective Lower House.\n2) Only the PM can recommend President's Rule under Article 356 of the Constitution.\nWhich of the statements is/are correct?",
    options: [
      { label: "A", text: "Only 1" },
      { label: "B", text: "Only 2" },
      { label: "C", text: "Both 1 and 2" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 41,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following pairs of type of nutrient – nutrient is correctly matched?",
    options: [
      { label: "A", text: "Micronutrient – Calcium" },
      { label: "B", text: "Macronutrient – Zinc" },
      { label: "C", text: "Micronutrient – Boron" },
      { label: "D", text: "Macronutrient – Iron" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 42,
    part: "B",
    partName: "General Awareness",
    questionText: "Which of the following pairs is correctly matched regarding electromagnetic devices?",
    options: [
      { label: "A", text: "Electric Generator : Converts electrical energy to mechanical energy." },
      { label: "B", text: "Transformer : Operates on DC current to change voltage." },
      { label: "C", text: "Electromagnet : A permanent magnet." },
      { label: "D", text: "Electric Bell : Uses the magnetic effect of electric current." },
    ],
    correctOption: "D",
  },
  {
    questionNo: 43,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the below statements marked as Assertion (A) and Reason (R). Mark the correct options:\nAssertion (A): Mission Amrit Sarovar promotes water conservation.\nReason (R): It aims to construct 75 ponds in each district by 2024.",
    options: [
      { label: "A", text: "Both A and R are true, and R is the correct explanation of A" },
      { label: "B", text: "Both A and R are true, but R is not the correct explanation of A" },
      { label: "C", text: "A is true, but R is false" },
      { label: "D", text: "A is false, but R is true" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 44,
    part: "B",
    partName: "General Awareness",
    questionText: "Consider the statements about Rauf:\n1. It is a women's group dance of Kashmir usually performed at Eid.\n2. Dancers align in two facing rows executing toe-heel footwork called ras.\nWhich is/are correct?",
    options: [
      { label: "A", text: "Only 1 correct" },
      { label: "B", text: "Only 2 correct" },
      { label: "C", text: "Both 1 & 2 correct" },
      { label: "D", text: "Neither 1 nor 2 correct" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 45,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the below statements marked as Assertion (A) and Reason (R). Mark the correct options:\nAssertion (A): India's rank in the Global Happiness Index is lower than most South Asian neighbours.\nReason (R): India's GDP per capita is the lowest in South Asia.",
    options: [
      { label: "A", text: "Both A and R are true, and R is the correct explanation of A." },
      { label: "B", text: "Both A and R are true, but R is not the correct explanation of A." },
      { label: "C", text: "A is true, but R is false." },
      { label: "D", text: "A is false, but R is true." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 46,
    part: "B",
    partName: "General Awareness",
    questionText: "Which Indian river was added to the National River Conservation Plan in 2024?",
    options: [
      { label: "A", text: "Yamuna" },
      { label: "B", text: "Musi" },
      { label: "C", text: "Krishna" },
      { label: "D", text: "Gomti" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 47,
    part: "B",
    partName: "General Awareness",
    questionText: "Article 50 is part of which section of the Constitution?",
    options: [
      { label: "A", text: "Fundamental Duties" },
      { label: "B", text: "Directive Principles of State Policy" },
      { label: "C", text: "Fundamental Rights" },
      { label: "D", text: "Preamble" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 48,
    part: "B",
    partName: "General Awareness",
    questionText: "Arrange the following in chronological order:\n1. GST Council constituted\n2. Constitution (101st Amendment) Act enacted\n3. GST launched\nChoose the correct chronological sequence:",
    options: [
      { label: "A", text: "1-2-3" },
      { label: "B", text: "2-1-3" },
      { label: "C", text: "3-2-1" },
      { label: "D", text: "2-3-1" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 49,
    part: "B",
    partName: "General Awareness",
    questionText: "Read the following Assertion (A) and Reason (R) carefully and choose the correct option.\nAssertion (A): The IPR 1956 created an industrial classification into Schedules A, B, and C.\nReason (R): This was to identify sectors for exclusive state control, joint sectors, and private sector operation.",
    options: [
      { label: "A", text: "Both A and R are true and R is the correct explanation of A." },
      { label: "B", text: "Both A and R are true but R is not the correct explanation of A." },
      { label: "C", text: "A is true but R is false." },
      { label: "D", text: "A is false but R is true." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 50,
    part: "B",
    partName: "General Awareness",
    questionText: "Regarding Earth's major climatic zones:\n1. Tropical zones experience minimal seasonal temperature variation\n2. Temperate zones are characterized by four distinct seasons.\nWhich of the above is/are correct?",
    options: [
      { label: "A", text: "Statement 1 only" },
      { label: "B", text: "Statement 2 only" },
      { label: "C", text: "Both 1 and 2" },
      { label: "D", text: "Neither 1 nor 2" },
    ],
    correctOption: "C",
  },

  // ===== PART C: Quantitative Aptitude (Q.51-Q.75) =====
  {
    questionNo: 51,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If P : Q = 6 : 11, Q : R = 5 : 4, and R : S = 9 : 7, find P : Q : R : S.",
    options: [
      { label: "A", text: "270 : 495 : 396 : 308" },
      { label: "B", text: "6 : 11 : 4 : 7" },
      { label: "C", text: "30 : 55 : 44 : 35" },
      { label: "D", text: "270 : 396 : 495 : 308" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 52,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A bag contains ₹10, ₹5, and ₹2 coins in the ratio 1 : 2 : 3. If the total amount of money in the bag is ₹390, find the number of coins of each kind.",
    options: [
      { label: "A", text: "10 coins of ₹10, 20 of ₹5, and 30 of ₹2" },
      { label: "B", text: "15 coins of ₹10, 30 of ₹5, and 45 of ₹2" },
      { label: "C", text: "20 coins of ₹10, 40 of ₹5, and 60 of ₹2" },
      { label: "D", text: "12 coins of ₹10, 24 of ₹5, and 36 of ₹2" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 53,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A tank holds 5¾ liters of water. If 2.375 liters are drained twice, how much water remains?",
    options: [
      { label: "A", text: "1" },
      { label: "B", text: "1¼" },
      { label: "C", text: "1⅜" },
      { label: "D", text: "1½" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 54,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: [(⅔) + (⁴⁄₅ ÷ ⅔)] ÷ [(³⁄₂) − (⅚ × ¾)]",
    options: [
      { label: "A", text: "416/105" },
      { label: "B", text: "418/110" },
      { label: "C", text: "425/250" },
      { label: "D", text: "526/350" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 55,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Simplify: (2½ + 3.6) ÷ 0.75 + (1.25 × ⅘)",
    options: [
      { label: "A", text: "137/15" },
      { label: "B", text: "160/15" },
      { label: "C", text: "127/15" },
      { label: "D", text: "148/15" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 56,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A and B invested in a business in the ratio 5:6. The profit ratio was 10:9. If B invested his money for 12 months, for how many months did A invest?",
    options: [
      { label: "A", text: "15 months" },
      { label: "B", text: "16 months" },
      { label: "C", text: "17 months" },
      { label: "D", text: "18 months" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 57,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "The average of 9 numbers is 56. When one number is removed, the average becomes 54. What number was removed?",
    options: [
      { label: "A", text: "52" },
      { label: "B", text: "72" },
      { label: "C", text: "82" },
      { label: "D", text: "92" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 58,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Table – Weekly Fuel Usage (litres):\nTruck1: Mon=18, Tue=20, Wed=22, Thu=21, Fri=19\nTruck2: Mon=25, Tue=24, Wed=26, Thu=23, Fri=24\nWhat is the overall average daily fuel usage for both trucks?",
    options: [
      { label: "A", text: "27 litres" },
      { label: "B", text: "22.2 litres" },
      { label: "C", text: "28 litres" },
      { label: "D", text: "21.5 litres" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 59,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A sum becomes ₹12100 in 2 years at 10% Compound Interest annually. Find the principal.",
    options: [
      { label: "A", text: "₹10000" },
      { label: "B", text: "₹11000" },
      { label: "C", text: "₹11500" },
      { label: "D", text: "₹10500" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 60,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A grocer purchased 50 kg of rice at ₹40 per kg and 20 kg of another variety of rice at ₹55 per kg. He mixed the two varieties and sold the entire mixture at ₹48 per kg. Find his total profit or loss in this transaction.",
    options: [
      { label: "A", text: "Loss of ₹260" },
      { label: "B", text: "Loss of ₹240" },
      { label: "C", text: "Profit of ₹260" },
      { label: "D", text: "Loss of ₹290" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 61,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A television set has a marked price of ₹20,000. It is sold after two successive discounts. If the first discount is 15% and the final selling price is ₹15,300, what is the percentage of the second discount?",
    options: [
      { label: "A", text: "10%" },
      { label: "B", text: "12%" },
      { label: "C", text: "14%" },
      { label: "D", text: "15%" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 62,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A manufacturer marked a product 30% above its cost price. He provided a discount to a customer, which resulted in him making a profit of 17%. What was the rate of discount given by the manufacturer?",
    options: [
      { label: "A", text: "24%" },
      { label: "B", text: "50%" },
      { label: "C", text: "60%" },
      { label: "D", text: "10%" },
    ],
    correctOption: "D",
  },
  {
    questionNo: 63,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two containers, A and B, contain mixtures of alcohol and water. Container A has alcohol and water in the ratio 4:1, while Container B has them in the ratio 5:2. If 10 liters are drawn from Container A and 14 liters from Container B, and the contents are mixed in a third container, what is the ratio of alcohol to water in the new mixture?",
    options: [
      { label: "A", text: "3:1" },
      { label: "B", text: "7:2" },
      { label: "C", text: "9:4" },
      { label: "D", text: "11:3" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 64,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If the radius of a sphere is increased to twice its original size, what is the ratio of the new surface area to the original surface area, as well as the proportion of the new volume to the original volume?",
    options: [
      { label: "A", text: "4:1 and 2:1" },
      { label: "B", text: "4:1 and 8:1" },
      { label: "C", text: "8:1 and 4:1" },
      { label: "D", text: "2:1 and 4:1" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 65,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A hemisphere and a cone share the same base and have equal volumes. Given that their common radius is R, determine the height of the cone.",
    options: [
      { label: "A", text: "2R" },
      { label: "B", text: "R" },
      { label: "C", text: "5R" },
      { label: "D", text: "4R" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 66,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A solid hemisphere of radius 10 cm is melted into two cones of equal height. If each cone's radius is 5 cm, what is the height of each cone?",
    options: [
      { label: "A", text: "40 cm" },
      { label: "B", text: "45 cm" },
      { label: "C", text: "50 cm" },
      { label: "D", text: "55 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 67,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "If base perimeter = 40 cm, slant height = 10 cm, what is lateral surface area of square pyramid?",
    options: [
      { label: "A", text: "260 cm²" },
      { label: "B", text: "200 cm²" },
      { label: "C", text: "400 cm²" },
      { label: "D", text: "432 cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 68,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two circular pizzas have radii in the ratio 2:3. If the smaller pizza has an area of 100π cm², what is the area of the larger pizza?",
    options: [
      { label: "A", text: "265π cm²" },
      { label: "B", text: "225π cm²" },
      { label: "C", text: "215π cm²" },
      { label: "D", text: "250π cm²" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 69,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "In a triangle ABC, medians AD and BE intersect at G. If the length of median AD is 12 cm, what is the length of the segment AG?",
    options: [
      { label: "A", text: "4 cm" },
      { label: "B", text: "6 cm" },
      { label: "C", text: "8 cm" },
      { label: "D", text: "9 cm" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 70,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two right-angled triangular blocks, ABC and DEF, have ∠B=∠E=90°. If the lengths of the hypotenuses AC and DF are equal, and the sides AB and DE are equal, are the triangles congruent? If so, by what rule?",
    options: [
      { label: "A", text: "Yes, by SSS" },
      { label: "B", text: "Yes, by SAS" },
      { label: "C", text: "Yes, by RHS" },
      { label: "D", text: "Yes, by ASA" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 71,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A right triangle ABC is inscribed in a circle with a diameter of 10 cm. An altitude BD is drawn from the vertex B to the hypotenuse AC. If the length of the leg AB is 6 cm, what is the length of the segment AD?",
    options: [
      { label: "A", text: "3.6 cm" },
      { label: "B", text: "4 cm" },
      { label: "C", text: "4.8 cm" },
      { label: "D", text: "6 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 72,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two circles intersect at two points. Which of the following statements is true?",
    options: [
      { label: "A", text: "The internal tangent is longer than the external tangent" },
      { label: "B", text: "Only two common tangents exist" },
      { label: "C", text: "The number of tangents depends on radii" },
      { label: "D", text: "They must be concentric" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 73,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "Two circles with radii r₁ and r₂ touch each other externally. If the length of their direct common tangent is T, which of the following is the correct relationship between T, r₁, and r₂?",
    options: [
      { label: "A", text: "T = r₁ + r₂" },
      { label: "B", text: "T = 2(r₁ + r₂)" },
      { label: "C", text: "T = 2√(r₁r₂)" },
      { label: "D", text: "T = r₁² + r₂²" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 74,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "A chord of a circle has a length of 12 cm. The angle subtended by the chord at a point on the circumference is 30°. What is the distance from the center of the circle to the chord?",
    options: [
      { label: "A", text: "6√3 cm" },
      { label: "B", text: "3√3 cm" },
      { label: "C", text: "6 cm" },
      { label: "D", text: "3 cm" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 75,
    part: "C",
    partName: "Quantitative Aptitude",
    questionText: "What is the area of the segment formed by a chord in a circle of radius 8 cm, if the angle subtended at the center is 60°?",
    options: [
      { label: "A", text: "32π/3 − 16√3" },
      { label: "B", text: "64π/3 − 16√3" },
      { label: "C", text: "32π/3 − 8√3" },
      { label: "D", text: "64π/3 − 32√3" },
    ],
    correctOption: "A",
  },

  // ===== PART D: English Comprehension (Q.76-Q.100) =====
  {
    questionNo: 76,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate synonym of the given word: ILLUMINATE",
    options: [
      { label: "A", text: "Explain" },
      { label: "B", text: "Darken" },
      { label: "C", text: "Destroy" },
      { label: "D", text: "Hide" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 77,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: Demur",
    options: [
      { label: "A", text: "Agree" },
      { label: "B", text: "Oppose" },
      { label: "C", text: "Object" },
      { label: "D", text: "Resist" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 78,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct meaning of idiom:\nEat humble pie",
    options: [
      { label: "A", text: "To demand an apology" },
      { label: "B", text: "To celebrate one's success" },
      { label: "C", text: "To accept insult or defeat gracefully" },
      { label: "D", text: "To prepare for failure" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 79,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the most appropriate antonym of the given word: Zany",
    options: [
      { label: "A", text: "Sensible" },
      { label: "B", text: "Bizarre" },
      { label: "C", text: "Clownish" },
      { label: "D", text: "Eccentric" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 80,
    part: "D",
    partName: "English Comprehension",
    questionText: "Spot the correct spelling of weather science.",
    options: [
      { label: "A", text: "Meterology" },
      { label: "B", text: "Meteorology" },
      { label: "C", text: "Meteorologie" },
      { label: "D", text: "Metereology" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 81,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitution for: 'A general pardon granted by a government'.",
    options: [
      { label: "A", text: "Amnesty" },
      { label: "B", text: "Reprieve" },
      { label: "C", text: "Clemency" },
      { label: "D", text: "Parole" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 82,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct one-word substitute for: 'A secret or disguised way of writing'.",
    options: [
      { label: "A", text: "Cipher" },
      { label: "B", text: "Epistle" },
      { label: "C", text: "Diatribe" },
      { label: "D", text: "Manuscript" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 83,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the correct phrasal verb:\nThe issue was so delicate that she chose to ____ it altogether.",
    options: [
      { label: "A", text: "brush aside" },
      { label: "B", text: "walk into" },
      { label: "C", text: "shy away from" },
      { label: "D", text: "lean over" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 84,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the correct option:\nThe artifact was notable not merely for its age but also for the ___ with which it was preserved.",
    options: [
      { label: "A", text: "meticulousness" },
      { label: "B", text: "velocity" },
      { label: "C", text: "brevity" },
      { label: "D", text: "severity" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 85,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nThe company needs a detailed feedback (1)/ from all departments (2)/ before finalising its restructuring plan (3)/ for the upcoming fiscal year. (4)/",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 86,
    part: "D",
    partName: "English Comprehension",
    questionText: "Change the following from active to passive:\nThe team will be revising the algorithms during the workshop.",
    options: [
      { label: "A", text: "The algorithms were being revised during the workshop." },
      { label: "B", text: "The algorithms will be been revised during the workshop." },
      { label: "C", text: "The algorithms will be revised during the workshop." },
      { label: "D", text: "The algorithms will be being revised during the workshop." },
    ],
    correctOption: "D",
  },
  {
    questionNo: 87,
    part: "D",
    partName: "English Comprehension",
    questionText: "Find the part of the sentence that contains an error:\nNot only the minister but also the bureaucrats (1)/ has been accused of manipulating (2)/ the data presented in the economic survey (3)/ to align with political interests. (4)",
    options: [
      { label: "A", text: "(1)" },
      { label: "B", text: "(2)" },
      { label: "C", text: "(3)" },
      { label: "D", text: "(4)" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 88,
    part: "D",
    partName: "English Comprehension",
    questionText: "Select the sentence containing the homonym of the highlighted word:\nThe architect discussed the vault beneath the cathedral.",
    options: [
      { label: "A", text: "The gymnast performed a perfect vault over the horse." },
      { label: "B", text: "The treasury vault was secured with biometric locks." },
      { label: "C", text: "The earthquake cracked the stone vault supporting the nave." },
      { label: "D", text: "The nobles were interred in the family vault." },
    ],
    correctOption: "A",
  },
  {
    questionNo: 89,
    part: "D",
    partName: "English Comprehension",
    questionText: "Convert the sentence provided below from its passive voice structure to an active voice structure:\nThe children were made to apologize by the principal for their behavior.",
    options: [
      { label: "A", text: "The principal was made to apologize to the children." },
      { label: "B", text: "The principal had made the children apologize." },
      { label: "C", text: "The principal made the children apologize for their behavior." },
      { label: "D", text: "The principal was apologizing to the children for their behavior." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 90,
    part: "D",
    partName: "English Comprehension",
    questionText: "What is the tone of the passage?",
    options: [
      { label: "A", text: "Didactic" },
      { label: "B", text: "Celebratory" },
      { label: "C", text: "Analytical" },
      { label: "D", text: "Flippant" },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 91,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which of the following best illustrates a paradox mentioned in the passage?",
    options: [
      { label: "A", text: "Technology enables cross-cultural empathy." },
      { label: "B", text: "Emojis unify people emotionally across cultures." },
      { label: "C", text: "Fluency in language can still lead to miscommunication." },
      { label: "D", text: "Humor is universally interpreted." },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 92,
    part: "D",
    partName: "English Comprehension",
    questionText: 'The phrase "semiotic dissonance" most likely refers to:',
    options: [
      { label: "A", text: "Discord in musical structure." },
      { label: "B", text: "Misinterpretation of cultural symbols and signs." },
      { label: "C", text: "Breakdown in Wi-Fi or digital signals." },
      { label: "D", text: "Agreement over symbolic meaning." },
    ],
    correctOption: "B",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 93,
    part: "D",
    partName: "English Comprehension",
    questionText: "Why might technology worsen intercultural communication, as per the author?",
    options: [
      { label: "A", text: "It amplifies real-time interaction." },
      { label: "B", text: "It removes the need for shared language." },
      { label: "C", text: "It flattens important non-verbal cues and misrepresents meaning." },
      { label: "D", text: "It encourages spontaneous expression." },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 94,
    part: "D",
    partName: "English Comprehension",
    questionText: "Which of the following metaphors best captures the overall argument of the passage?",
    options: [
      { label: "A", text: "A bridge that never meets the other side." },
      { label: "B", text: "A mirror reflecting only half the image." },
      { label: "C", text: "A labyrinth filled with shifting doors." },
      { label: "D", text: "A ladder leading to one clear peak." },
    ],
    correctOption: "C",
    passage: PASSAGE_90_94,
  },
  {
    questionNo: 95,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nWe enjoyed very much at the party.",
    options: [
      { label: "A", text: "have enjoyed very much" },
      { label: "B", text: "enjoyed ourselves very much" },
      { label: "C", text: "enjoyed at the party" },
      { label: "D", text: "were enjoyed" },
    ],
    correctOption: "B",
  },
  {
    questionNo: 96,
    part: "D",
    partName: "English Comprehension",
    questionText: "Choose the most suitable option to replace the highlighted part of the sentence:\nNeither the manager nor the employees was available.",
    options: [
      { label: "A", text: "was not available" },
      { label: "B", text: "were also available" },
      { label: "C", text: "were available" },
      { label: "D", text: "was also not available" },
    ],
    correctOption: "C",
  },
  {
    questionNo: 97,
    part: "D",
    partName: "English Comprehension",
    questionText: 'A sentence is provided in direct speech. From the four given options, choose the one that most accurately conveys the sentence in its corresponding indirect speech.\nShe said, "I can solve this problem."',
    options: [
      { label: "A", text: "She said that she will solve that problem." },
      { label: "B", text: "She said that she could solve this problem." },
      { label: "C", text: "She said that she could solve that problem." },
      { label: "D", text: "She said she can solve the problem." },
    ],
    correctOption: "C",
  },
  {
    questionNo: 98,
    part: "D",
    partName: "English Comprehension",
    questionText: "A sentence is provided in indirect speech. From the four given options, choose the one that most accurately conveys the sentence in its corresponding direct speech.\nShe said that she used to play the violin when she was young.",
    options: [
      { label: "A", text: '"I played the violin when I was young," she said.' },
      { label: "B", text: '"I use to play the violin when I was young," she said.' },
      { label: "C", text: '"I used to play the violin when I was young," she said.' },
      { label: "D", text: '"I was playing the violin when I was young," she said.' },
    ],
    correctOption: "C",
  },
  {
    questionNo: 99,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. This is especially useful in software development, where multiple programmers can work on the same codebase simultaneously without conflict.\n2. Version control is a system that records changes to a file or set of files over time so that you can recall specific versions later.\n3. The process involves a specific set of tools and commands that allow for the manipulation and tracking of changes.\n4. By using version control, a project can maintain a complete history of its development, allowing for easy rollback and collaboration.",
    options: [
      { label: "A", text: "2, 4, 3, 1" },
      { label: "B", text: "2, 3, 4, 1" },
      { label: "C", text: "3, 2, 4, 1" },
      { label: "D", text: "4, 1, 2, 3" },
    ],
    correctOption: "A",
  },
  {
    questionNo: 100,
    part: "D",
    partName: "English Comprehension",
    questionText: "Rearrange the following sentences to form a coherent paragraph:\n1. This is especially useful in software development, where multiple programmers can work on the same codebase simultaneously without conflict.\n2. Version control is a system that records changes to a file or set of files over time so that you can recall specific versions later.\n3. The process involves a specific set of tools and commands that allow for the manipulation and tracking of changes.\n4. By using version control, a project can maintain a complete history of its development, allowing for easy rollback and collaboration.",
    options: [
      { label: "A", text: "2, 4, 3, 1" },
      { label: "B", text: "2, 3, 4, 1" },
      { label: "C", text: "3, 2, 4, 1" },
      { label: "D", text: "4, 1, 2, 3" },
    ],
    correctOption: "A",
  },
];
